/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Add</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.softtek.rdl.RdlPackage#getActionAdd()
 * @model
 * @generated
 */
public interface ActionAdd extends Action
{
} // ActionAdd
