/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DATE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.DATE#getDate <em>Date</em>}</li>
 *   <li>{@link com.softtek.rdl.DATE#getNow <em>Now</em>}</li>
 * </ul>
 *
 * @see com.softtek.rdl.RdlPackage#getDATE()
 * @model
 * @generated
 */
public interface DATE extends EObject
{
  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Date</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute.
   * @see #setDate(String)
   * @see com.softtek.rdl.RdlPackage#getDATE_Date()
   * @model
   * @generated
   */
  String getDate();

  /**
   * Sets the value of the '{@link com.softtek.rdl.DATE#getDate <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' attribute.
   * @see #getDate()
   * @generated
   */
  void setDate(String value);

  /**
   * Returns the value of the '<em><b>Now</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Now</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Now</em>' attribute.
   * @see #setNow(String)
   * @see com.softtek.rdl.RdlPackage#getDATE_Now()
   * @model
   * @generated
   */
  String getNow();

  /**
   * Sets the value of the '{@link com.softtek.rdl.DATE#getNow <em>Now</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Now</em>' attribute.
   * @see #getNow()
   * @generated
   */
  void setNow(String value);

} // DATE
