/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DB Map Attr Auto Id</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.DBMapAttrAutoId#getAutoid <em>Autoid</em>}</li>
 * </ul>
 *
 * @see com.softtek.rdl.RdlPackage#getDBMapAttrAutoId()
 * @model
 * @generated
 */
public interface DBMapAttrAutoId extends DBMapAttr
{
  /**
   * Returns the value of the '<em><b>Autoid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Autoid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Autoid</em>' attribute.
   * @see #setAutoid(String)
   * @see com.softtek.rdl.RdlPackage#getDBMapAttrAutoId_Autoid()
   * @model
   * @generated
   */
  String getAutoid();

  /**
   * Sets the value of the '{@link com.softtek.rdl.DBMapAttrAutoId#getAutoid <em>Autoid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Autoid</em>' attribute.
   * @see #getAutoid()
   * @generated
   */
  void setAutoid(String value);

} // DBMapAttrAutoId
