/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DB Map Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.DBMapEntity#getTable <em>Table</em>}</li>
 *   <li>{@link com.softtek.rdl.DBMapEntity#getDbmap_attrs <em>Dbmap attrs</em>}</li>
 * </ul>
 *
 * @see com.softtek.rdl.RdlPackage#getDBMapEntity()
 * @model
 * @generated
 */
public interface DBMapEntity extends EObject
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Table</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' attribute.
   * @see #setTable(String)
   * @see com.softtek.rdl.RdlPackage#getDBMapEntity_Table()
   * @model
   * @generated
   */
  String getTable();

  /**
   * Sets the value of the '{@link com.softtek.rdl.DBMapEntity#getTable <em>Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' attribute.
   * @see #getTable()
   * @generated
   */
  void setTable(String value);

  /**
   * Returns the value of the '<em><b>Dbmap attrs</b></em>' containment reference list.
   * The list contents are of type {@link com.softtek.rdl.DBMapAttr}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dbmap attrs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dbmap attrs</em>' containment reference list.
   * @see com.softtek.rdl.RdlPackage#getDBMapEntity_Dbmap_attrs()
   * @model containment="true"
   * @generated
   */
  EList<DBMapAttr> getDbmap_attrs();

} // DBMapEntity
