/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Text Constraint Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.EntityTextConstraintDef#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @see com.softtek.rdl.RdlPackage#getEntityTextConstraintDef()
 * @model
 * @generated
 */
public interface EntityTextConstraintDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference list.
   * The list contents are of type {@link com.softtek.rdl.EntityTextConstraint}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraints</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference list.
   * @see com.softtek.rdl.RdlPackage#getEntityTextConstraintDef_Constraints()
   * @model containment="true"
   * @generated
   */
  EList<EntityTextConstraint> getConstraints();

} // EntityTextConstraintDef
