/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.Entity#getName <em>Name</em>}</li>
 *   <li>{@link com.softtek.rdl.Entity#getActions <em>Actions</em>}</li>
 *   <li>{@link com.softtek.rdl.Entity#getGlossary <em>Glossary</em>}</li>
 *   <li>{@link com.softtek.rdl.Entity#getDb_map <em>Db map</em>}</li>
 *   <li>{@link com.softtek.rdl.Entity#getEntity_fields <em>Entity fields</em>}</li>
 *   <li>{@link com.softtek.rdl.Entity#getEntity_methods <em>Entity methods</em>}</li>
 * </ul>
 *
 * @see com.softtek.rdl.RdlPackage#getEntity()
 * @model
 * @generated
 */
public interface Entity extends AbstractElement, EnumEntity
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.softtek.rdl.RdlPackage#getEntity_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.softtek.rdl.Entity#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actions</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference.
   * @see #setActions(Actions)
   * @see com.softtek.rdl.RdlPackage#getEntity_Actions()
   * @model containment="true"
   * @generated
   */
  Actions getActions();

  /**
   * Sets the value of the '{@link com.softtek.rdl.Entity#getActions <em>Actions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actions</em>' containment reference.
   * @see #getActions()
   * @generated
   */
  void setActions(Actions value);

  /**
   * Returns the value of the '<em><b>Glossary</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Glossary</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Glossary</em>' containment reference.
   * @see #setGlossary(Glossary)
   * @see com.softtek.rdl.RdlPackage#getEntity_Glossary()
   * @model containment="true"
   * @generated
   */
  Glossary getGlossary();

  /**
   * Sets the value of the '{@link com.softtek.rdl.Entity#getGlossary <em>Glossary</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Glossary</em>' containment reference.
   * @see #getGlossary()
   * @generated
   */
  void setGlossary(Glossary value);

  /**
   * Returns the value of the '<em><b>Db map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Db map</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db map</em>' containment reference.
   * @see #setDb_map(DBMapEntity)
   * @see com.softtek.rdl.RdlPackage#getEntity_Db_map()
   * @model containment="true"
   * @generated
   */
  DBMapEntity getDb_map();

  /**
   * Sets the value of the '{@link com.softtek.rdl.Entity#getDb_map <em>Db map</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db map</em>' containment reference.
   * @see #getDb_map()
   * @generated
   */
  void setDb_map(DBMapEntity value);

  /**
   * Returns the value of the '<em><b>Entity fields</b></em>' containment reference list.
   * The list contents are of type {@link com.softtek.rdl.EntityField}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entity fields</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity fields</em>' containment reference list.
   * @see com.softtek.rdl.RdlPackage#getEntity_Entity_fields()
   * @model containment="true"
   * @generated
   */
  EList<EntityField> getEntity_fields();

  /**
   * Returns the value of the '<em><b>Entity methods</b></em>' containment reference list.
   * The list contents are of type {@link com.softtek.rdl.MethodDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entity methods</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity methods</em>' containment reference list.
   * @see com.softtek.rdl.RdlPackage#getEntity_Entity_methods()
   * @model containment="true"
   * @generated
   */
  EList<MethodDeclaration> getEntity_methods();

} // Entity
