/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Text Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.softtek.rdl.RdlPackage#getEntityTextConstraint()
 * @model
 * @generated
 */
public interface EntityTextConstraint extends EObject
{
} // EntityTextConstraint
