/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.softtek.rdl.RdlPackage#getEnumEntity()
 * @model
 * @generated
 */
public interface EnumEntity extends EObject
{
} // EnumEntity
