/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.MethodDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link com.softtek.rdl.MethodDeclaration#getDef_statements <em>Def statements</em>}</li>
 * </ul>
 *
 * @see com.softtek.rdl.RdlPackage#getMethodDeclaration()
 * @model
 * @generated
 */
public interface MethodDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.softtek.rdl.RdlPackage#getMethodDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.softtek.rdl.MethodDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Def statements</b></em>' containment reference list.
   * The list contents are of type {@link com.softtek.rdl.Statement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Def statements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def statements</em>' containment reference list.
   * @see com.softtek.rdl.RdlPackage#getMethodDeclaration_Def_statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getDef_statements();

} // MethodDeclaration
