/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.softtek.rdl.RdlPackage
 * @generated
 */
public interface RdlFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RdlFactory eINSTANCE = com.softtek.rdl.impl.RdlFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Module</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Module</em>'.
   * @generated
   */
  Module createModule();

  /**
   * Returns a new object of class '<em>Abstract Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Element</em>'.
   * @generated
   */
  AbstractElement createAbstractElement();

  /**
   * Returns a new object of class '<em>Enum</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum</em>'.
   * @generated
   */
  Enum createEnum();

  /**
   * Returns a new object of class '<em>Enum Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum Literal</em>'.
   * @generated
   */
  EnumLiteral createEnumLiteral();

  /**
   * Returns a new object of class '<em>Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity</em>'.
   * @generated
   */
  Entity createEntity();

  /**
   * Returns a new object of class '<em>Method Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Declaration</em>'.
   * @generated
   */
  MethodDeclaration createMethodDeclaration();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>Statement Return</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Return</em>'.
   * @generated
   */
  StatementReturn createStatementReturn();

  /**
   * Returns a new object of class '<em>Entity Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Field</em>'.
   * @generated
   */
  EntityField createEntityField();

  /**
   * Returns a new object of class '<em>Entity Text Constraint Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Text Constraint Def</em>'.
   * @generated
   */
  EntityTextConstraintDef createEntityTextConstraintDef();

  /**
   * Returns a new object of class '<em>Entity Text Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Text Constraint</em>'.
   * @generated
   */
  EntityTextConstraint createEntityTextConstraint();

  /**
   * Returns a new object of class '<em>Entity Text Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Text Field</em>'.
   * @generated
   */
  EntityTextField createEntityTextField();

  /**
   * Returns a new object of class '<em>Entity Text Field Attr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Text Field Attr</em>'.
   * @generated
   */
  EntityTextFieldAttr createEntityTextFieldAttr();

  /**
   * Returns a new object of class '<em>Entity Long Text Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Long Text Field</em>'.
   * @generated
   */
  EntityLongTextField createEntityLongTextField();

  /**
   * Returns a new object of class '<em>Entity Long Text Field Attr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Long Text Field Attr</em>'.
   * @generated
   */
  EntityLongTextFieldAttr createEntityLongTextFieldAttr();

  /**
   * Returns a new object of class '<em>Entity Date Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Date Field</em>'.
   * @generated
   */
  EntityDateField createEntityDateField();

  /**
   * Returns a new object of class '<em>Entity Date Field Attr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Date Field Attr</em>'.
   * @generated
   */
  EntityDateFieldAttr createEntityDateFieldAttr();

  /**
   * Returns a new object of class '<em>Entity Reference Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Reference Field</em>'.
   * @generated
   */
  EntityReferenceField createEntityReferenceField();

  /**
   * Returns a new object of class '<em>Entity Reference Field Attr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Reference Field Attr</em>'.
   * @generated
   */
  EntityReferenceFieldAttr createEntityReferenceFieldAttr();

  /**
   * Returns a new object of class '<em>Enum Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum Entity</em>'.
   * @generated
   */
  EnumEntity createEnumEntity();

  /**
   * Returns a new object of class '<em>Entity Image Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Image Field</em>'.
   * @generated
   */
  EntityImageField createEntityImageField();

  /**
   * Returns a new object of class '<em>Entity File Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity File Field</em>'.
   * @generated
   */
  EntityFileField createEntityFileField();

  /**
   * Returns a new object of class '<em>Entity Email Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Email Field</em>'.
   * @generated
   */
  EntityEmailField createEntityEmailField();

  /**
   * Returns a new object of class '<em>Entity Decimal Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Decimal Field</em>'.
   * @generated
   */
  EntityDecimalField createEntityDecimalField();

  /**
   * Returns a new object of class '<em>Entity Integer Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Integer Field</em>'.
   * @generated
   */
  EntityIntegerField createEntityIntegerField();

  /**
   * Returns a new object of class '<em>Entity Currency Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Currency Field</em>'.
   * @generated
   */
  EntityCurrencyField createEntityCurrencyField();

  /**
   * Returns a new object of class '<em>Entity Attr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Attr</em>'.
   * @generated
   */
  EntityAttr createEntityAttr();

  /**
   * Returns a new object of class '<em>Constraint Required</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint Required</em>'.
   * @generated
   */
  ConstraintRequired createConstraintRequired();

  /**
   * Returns a new object of class '<em>Constraint Unique</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint Unique</em>'.
   * @generated
   */
  ConstraintUnique createConstraintUnique();

  /**
   * Returns a new object of class '<em>Constraint Max Length</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint Max Length</em>'.
   * @generated
   */
  ConstraintMaxLength createConstraintMaxLength();

  /**
   * Returns a new object of class '<em>Constraint Min Length</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint Min Length</em>'.
   * @generated
   */
  ConstraintMinLength createConstraintMinLength();

  /**
   * Returns a new object of class '<em>Glossary</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Glossary</em>'.
   * @generated
   */
  Glossary createGlossary();

  /**
   * Returns a new object of class '<em>Glossary Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Glossary Name</em>'.
   * @generated
   */
  GlossaryName createGlossaryName();

  /**
   * Returns a new object of class '<em>Glossary Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Glossary Description</em>'.
   * @generated
   */
  GlossaryDescription createGlossaryDescription();

  /**
   * Returns a new object of class '<em>Widget Label</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Label</em>'.
   * @generated
   */
  WidgetLabel createWidgetLabel();

  /**
   * Returns a new object of class '<em>Widget Help</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Help</em>'.
   * @generated
   */
  WidgetHelp createWidgetHelp();

  /**
   * Returns a new object of class '<em>Widget Exposed Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Exposed Filter</em>'.
   * @generated
   */
  WidgetExposedFilter createWidgetExposedFilter();

  /**
   * Returns a new object of class '<em>Widget Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Type</em>'.
   * @generated
   */
  WidgetType createWidgetType();

  /**
   * Returns a new object of class '<em>Widget Type Select</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Type Select</em>'.
   * @generated
   */
  WidgetTypeSelect createWidgetTypeSelect();

  /**
   * Returns a new object of class '<em>Widget Sort By</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Sort By</em>'.
   * @generated
   */
  WidgetSortBy createWidgetSortBy();

  /**
   * Returns a new object of class '<em>Widget Start Year</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Start Year</em>'.
   * @generated
   */
  WidgetStartYear createWidgetStartYear();

  /**
   * Returns a new object of class '<em>Widget End Year</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget End Year</em>'.
   * @generated
   */
  WidgetEndYear createWidgetEndYear();

  /**
   * Returns a new object of class '<em>Widget</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget</em>'.
   * @generated
   */
  Widget createWidget();

  /**
   * Returns a new object of class '<em>Widget Enum</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Enum</em>'.
   * @generated
   */
  WidgetEnum createWidgetEnum();

  /**
   * Returns a new object of class '<em>Widget Date</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Date</em>'.
   * @generated
   */
  WidgetDate createWidgetDate();

  /**
   * Returns a new object of class '<em>Widget Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Text</em>'.
   * @generated
   */
  WidgetText createWidgetText();

  /**
   * Returns a new object of class '<em>Widget Attr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Attr</em>'.
   * @generated
   */
  WidgetAttr createWidgetAttr();

  /**
   * Returns a new object of class '<em>Widget Attr Enum</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Attr Enum</em>'.
   * @generated
   */
  WidgetAttrEnum createWidgetAttrEnum();

  /**
   * Returns a new object of class '<em>Widget Attr Enum Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Attr Enum Type</em>'.
   * @generated
   */
  WidgetAttrEnumType createWidgetAttrEnumType();

  /**
   * Returns a new object of class '<em>Widget Attr Enum Type Select</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Attr Enum Type Select</em>'.
   * @generated
   */
  WidgetAttrEnumTypeSelect createWidgetAttrEnumTypeSelect();

  /**
   * Returns a new object of class '<em>Widget Attr Date</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Attr Date</em>'.
   * @generated
   */
  WidgetAttrDate createWidgetAttrDate();

  /**
   * Returns a new object of class '<em>Widget Attr Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Attr Text</em>'.
   * @generated
   */
  WidgetAttrText createWidgetAttrText();

  /**
   * Returns a new object of class '<em>Widget Size</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Size</em>'.
   * @generated
   */
  WidgetSize createWidgetSize();

  /**
   * Returns a new object of class '<em>Widget Display Result</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Widget Display Result</em>'.
   * @generated
   */
  WidgetDisplayResult createWidgetDisplayResult();

  /**
   * Returns a new object of class '<em>DATE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DATE</em>'.
   * @generated
   */
  DATE createDATE();

  /**
   * Returns a new object of class '<em>Action Search</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Search</em>'.
   * @generated
   */
  ActionSearch createActionSearch();

  /**
   * Returns a new object of class '<em>Action Add</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Add</em>'.
   * @generated
   */
  ActionAdd createActionAdd();

  /**
   * Returns a new object of class '<em>Action Edit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Edit</em>'.
   * @generated
   */
  ActionEdit createActionEdit();

  /**
   * Returns a new object of class '<em>Action Delete</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Delete</em>'.
   * @generated
   */
  ActionDelete createActionDelete();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Actions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Actions</em>'.
   * @generated
   */
  Actions createActions();

  /**
   * Returns a new object of class '<em>DB Map Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DB Map Entity</em>'.
   * @generated
   */
  DBMapEntity createDBMapEntity();

  /**
   * Returns a new object of class '<em>DB Map Attr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DB Map Attr</em>'.
   * @generated
   */
  DBMapAttr createDBMapAttr();

  /**
   * Returns a new object of class '<em>DB Map Attr Identity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DB Map Attr Identity</em>'.
   * @generated
   */
  DBMapAttrIdentity createDBMapAttrIdentity();

  /**
   * Returns a new object of class '<em>DB Map Attr Auto Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DB Map Attr Auto Id</em>'.
   * @generated
   */
  DBMapAttrAutoId createDBMapAttrAutoId();

  /**
   * Returns a new object of class '<em>DB Map Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DB Map Field</em>'.
   * @generated
   */
  DBMapField createDBMapField();

  /**
   * Returns a new object of class '<em>Data Domain</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Domain</em>'.
   * @generated
   */
  DataDomain createDataDomain();

  /**
   * Returns a new object of class '<em>Business Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Business Rule</em>'.
   * @generated
   */
  BusinessRule createBusinessRule();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  RdlPackage getRdlPackage();

} //RdlFactory
