/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Widget Attr Enum Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.softtek.rdl.RdlPackage#getWidgetAttrEnumType()
 * @model
 * @generated
 */
public interface WidgetAttrEnumType extends WidgetAttrEnum
{
} // WidgetAttrEnumType
