/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Widget Start Year</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.WidgetStartYear#getStart <em>Start</em>}</li>
 * </ul>
 *
 * @see com.softtek.rdl.RdlPackage#getWidgetStartYear()
 * @model
 * @generated
 */
public interface WidgetStartYear extends WidgetAttrDate
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' attribute.
   * @see #setStart(String)
   * @see com.softtek.rdl.RdlPackage#getWidgetStartYear_Start()
   * @model
   * @generated
   */
  String getStart();

  /**
   * Sets the value of the '{@link com.softtek.rdl.WidgetStartYear#getStart <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' attribute.
   * @see #getStart()
   * @generated
   */
  void setStart(String value);

} // WidgetStartYear
