/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Widget End Year</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.WidgetEndYear#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see com.softtek.rdl.RdlPackage#getWidgetEndYear()
 * @model
 * @generated
 */
public interface WidgetEndYear extends WidgetAttrDate
{
  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see #setEnd(String)
   * @see com.softtek.rdl.RdlPackage#getWidgetEndYear_End()
   * @model
   * @generated
   */
  String getEnd();

  /**
   * Sets the value of the '{@link com.softtek.rdl.WidgetEndYear#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see #getEnd()
   * @generated
   */
  void setEnd(String value);

} // WidgetEndYear
