/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Widget Exposed Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.WidgetExposedFilter#getExposed_filter <em>Exposed filter</em>}</li>
 * </ul>
 *
 * @see com.softtek.rdl.RdlPackage#getWidgetExposedFilter()
 * @model
 * @generated
 */
public interface WidgetExposedFilter extends WidgetAttr, WidgetAttrEnumType, WidgetAttrDate, WidgetAttrText
{
  /**
   * Returns the value of the '<em><b>Exposed filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exposed filter</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exposed filter</em>' attribute.
   * @see #setExposed_filter(String)
   * @see com.softtek.rdl.RdlPackage#getWidgetExposedFilter_Exposed_filter()
   * @model
   * @generated
   */
  String getExposed_filter();

  /**
   * Sets the value of the '{@link com.softtek.rdl.WidgetExposedFilter#getExposed_filter <em>Exposed filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exposed filter</em>' attribute.
   * @see #getExposed_filter()
   * @generated
   */
  void setExposed_filter(String value);

} // WidgetExposedFilter
