/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Widget Sort By</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.WidgetSortBy#getSortby <em>Sortby</em>}</li>
 * </ul>
 *
 * @see com.softtek.rdl.RdlPackage#getWidgetSortBy()
 * @model
 * @generated
 */
public interface WidgetSortBy extends EObject
{
  /**
   * Returns the value of the '<em><b>Sortby</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sortby</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sortby</em>' attribute.
   * @see #setSortby(String)
   * @see com.softtek.rdl.RdlPackage#getWidgetSortBy_Sortby()
   * @model
   * @generated
   */
  String getSortby();

  /**
   * Sets the value of the '{@link com.softtek.rdl.WidgetSortBy#getSortby <em>Sortby</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sortby</em>' attribute.
   * @see #getSortby()
   * @generated
   */
  void setSortby(String value);

} // WidgetSortBy
