/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl.impl;

import com.softtek.rdl.EntityTextConstraint;
import com.softtek.rdl.RdlPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entity Text Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EntityTextConstraintImpl extends MinimalEObjectImpl.Container implements EntityTextConstraint
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntityTextConstraintImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdlPackage.Literals.ENTITY_TEXT_CONSTRAINT;
  }

} //EntityTextConstraintImpl
