/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl.impl;

import com.softtek.rdl.AbstractElement;
import com.softtek.rdl.Action;
import com.softtek.rdl.ActionAdd;
import com.softtek.rdl.ActionDelete;
import com.softtek.rdl.ActionEdit;
import com.softtek.rdl.ActionSearch;
import com.softtek.rdl.Actions;
import com.softtek.rdl.BusinessRule;
import com.softtek.rdl.ConstraintMaxLength;
import com.softtek.rdl.ConstraintMinLength;
import com.softtek.rdl.ConstraintRequired;
import com.softtek.rdl.ConstraintUnique;
import com.softtek.rdl.DBMapAttr;
import com.softtek.rdl.DBMapAttrAutoId;
import com.softtek.rdl.DBMapAttrIdentity;
import com.softtek.rdl.DBMapEntity;
import com.softtek.rdl.DBMapField;
import com.softtek.rdl.DataDomain;
import com.softtek.rdl.Entity;
import com.softtek.rdl.EntityAttr;
import com.softtek.rdl.EntityCurrencyField;
import com.softtek.rdl.EntityDateField;
import com.softtek.rdl.EntityDateFieldAttr;
import com.softtek.rdl.EntityDecimalField;
import com.softtek.rdl.EntityEmailField;
import com.softtek.rdl.EntityField;
import com.softtek.rdl.EntityFileField;
import com.softtek.rdl.EntityImageField;
import com.softtek.rdl.EntityIntegerField;
import com.softtek.rdl.EntityLongTextField;
import com.softtek.rdl.EntityLongTextFieldAttr;
import com.softtek.rdl.EntityReferenceField;
import com.softtek.rdl.EntityReferenceFieldAttr;
import com.softtek.rdl.EntityTextConstraint;
import com.softtek.rdl.EntityTextConstraintDef;
import com.softtek.rdl.EntityTextField;
import com.softtek.rdl.EntityTextFieldAttr;
import com.softtek.rdl.EnumEntity;
import com.softtek.rdl.EnumLiteral;
import com.softtek.rdl.Glossary;
import com.softtek.rdl.GlossaryDescription;
import com.softtek.rdl.GlossaryName;
import com.softtek.rdl.MethodDeclaration;
import com.softtek.rdl.Model;
import com.softtek.rdl.Module;
import com.softtek.rdl.RdlFactory;
import com.softtek.rdl.RdlPackage;
import com.softtek.rdl.Statement;
import com.softtek.rdl.StatementReturn;
import com.softtek.rdl.Widget;
import com.softtek.rdl.WidgetAttr;
import com.softtek.rdl.WidgetAttrDate;
import com.softtek.rdl.WidgetAttrEnum;
import com.softtek.rdl.WidgetAttrEnumType;
import com.softtek.rdl.WidgetAttrEnumTypeSelect;
import com.softtek.rdl.WidgetAttrText;
import com.softtek.rdl.WidgetDate;
import com.softtek.rdl.WidgetDisplayResult;
import com.softtek.rdl.WidgetEndYear;
import com.softtek.rdl.WidgetEnum;
import com.softtek.rdl.WidgetExposedFilter;
import com.softtek.rdl.WidgetHelp;
import com.softtek.rdl.WidgetLabel;
import com.softtek.rdl.WidgetSize;
import com.softtek.rdl.WidgetSortBy;
import com.softtek.rdl.WidgetStartYear;
import com.softtek.rdl.WidgetText;
import com.softtek.rdl.WidgetType;
import com.softtek.rdl.WidgetTypeSelect;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class RdlPackageImpl extends EPackageImpl implements RdlPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moduleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass abstractElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass enumEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass enumLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass methodDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass statementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass statementReturnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityTextConstraintDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityTextConstraintEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityTextFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityTextFieldAttrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityLongTextFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityLongTextFieldAttrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityDateFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityDateFieldAttrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityReferenceFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityReferenceFieldAttrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass enumEntityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityImageFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityFileFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityEmailFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityDecimalFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityIntegerFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityCurrencyFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityAttrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constraintRequiredEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constraintUniqueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constraintMaxLengthEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constraintMinLengthEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass glossaryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass glossaryNameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass glossaryDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetLabelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetHelpEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetExposedFilterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetTypeSelectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetSortByEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetStartYearEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetEndYearEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetEnumEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetDateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetTextEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetAttrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetAttrEnumEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetAttrEnumTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetAttrEnumTypeSelectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetAttrDateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetAttrTextEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetSizeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widgetDisplayResultEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionSearchEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionAddEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionEditEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionDeleteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dbMapEntityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dbMapAttrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dbMapAttrIdentityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dbMapAttrAutoIdEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dbMapFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dataDomainEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass businessRuleEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see com.softtek.rdl.RdlPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private RdlPackageImpl()
  {
    super(eNS_URI, RdlFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link RdlPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static RdlPackage init()
  {
    if (isInited) return (RdlPackage)EPackage.Registry.INSTANCE.getEPackage(RdlPackage.eNS_URI);

    // Obtain or create and register package
    RdlPackageImpl theRdlPackage = (RdlPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof RdlPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new RdlPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theRdlPackage.createPackageContents();

    // Initialize created meta-data
    theRdlPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theRdlPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(RdlPackage.eNS_URI, theRdlPackage);
    return theRdlPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Module()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModule()
  {
    return moduleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getModule_Name()
  {
    return (EAttribute)moduleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModule_Elements()
  {
    return (EReference)moduleEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAbstractElement()
  {
    return abstractElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEnum()
  {
    return enumEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEnum_Name()
  {
    return (EAttribute)enumEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEnum_Enum_literals()
  {
    return (EReference)enumEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEnumLiteral()
  {
    return enumLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEnumLiteral_Key()
  {
    return (EAttribute)enumLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEnumLiteral_Value()
  {
    return (EAttribute)enumLiteralEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntity()
  {
    return entityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEntity_Name()
  {
    return (EAttribute)entityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntity_Actions()
  {
    return (EReference)entityEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntity_Glossary()
  {
    return (EReference)entityEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntity_Db_map()
  {
    return (EReference)entityEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntity_Entity_fields()
  {
    return (EReference)entityEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntity_Entity_methods()
  {
    return (EReference)entityEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMethodDeclaration()
  {
    return methodDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMethodDeclaration_Name()
  {
    return (EAttribute)methodDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMethodDeclaration_Def_statements()
  {
    return (EReference)methodDeclarationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getStatement()
  {
    return statementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getStatementReturn()
  {
    return statementReturnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getStatementReturn_Entityfield()
  {
    return (EReference)statementReturnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityField()
  {
    return entityFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEntityField_Name()
  {
    return (EAttribute)entityFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityTextConstraintDef()
  {
    return entityTextConstraintDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityTextConstraintDef_Constraints()
  {
    return (EReference)entityTextConstraintDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityTextConstraint()
  {
    return entityTextConstraintEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityTextField()
  {
    return entityTextFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityTextField_Attrs()
  {
    return (EReference)entityTextFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityTextFieldAttr()
  {
    return entityTextFieldAttrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityTextFieldAttr_Glossary()
  {
    return (EReference)entityTextFieldAttrEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityTextFieldAttr_Widget()
  {
    return (EReference)entityTextFieldAttrEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityTextFieldAttr_Constraint()
  {
    return (EReference)entityTextFieldAttrEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityTextFieldAttr_Db_map()
  {
    return (EReference)entityTextFieldAttrEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityTextFieldAttr_Data_domain()
  {
    return (EReference)entityTextFieldAttrEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityTextFieldAttr_Business_rule()
  {
    return (EReference)entityTextFieldAttrEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityLongTextField()
  {
    return entityLongTextFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityLongTextField_Attrs()
  {
    return (EReference)entityLongTextFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityLongTextFieldAttr()
  {
    return entityLongTextFieldAttrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityLongTextFieldAttr_Glossary()
  {
    return (EReference)entityLongTextFieldAttrEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityLongTextFieldAttr_Widget()
  {
    return (EReference)entityLongTextFieldAttrEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityLongTextFieldAttr_Constraint()
  {
    return (EReference)entityLongTextFieldAttrEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityLongTextFieldAttr_Db_map()
  {
    return (EReference)entityLongTextFieldAttrEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityLongTextFieldAttr_Data_domain()
  {
    return (EReference)entityLongTextFieldAttrEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityLongTextFieldAttr_Business_rule()
  {
    return (EReference)entityLongTextFieldAttrEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityDateField()
  {
    return entityDateFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityDateField_Attrs()
  {
    return (EReference)entityDateFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityDateFieldAttr()
  {
    return entityDateFieldAttrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityDateFieldAttr_Default()
  {
    return (EReference)entityDateFieldAttrEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityDateFieldAttr_Glossary()
  {
    return (EReference)entityDateFieldAttrEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityDateFieldAttr_Widget()
  {
    return (EReference)entityDateFieldAttrEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityDateFieldAttr_Constraint()
  {
    return (EReference)entityDateFieldAttrEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityDateFieldAttr_Db_map()
  {
    return (EReference)entityDateFieldAttrEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityDateFieldAttr_Data_domain()
  {
    return (EReference)entityDateFieldAttrEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityDateFieldAttr_Business_rule()
  {
    return (EReference)entityDateFieldAttrEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityReferenceField()
  {
    return entityReferenceFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityReferenceField_SuperType()
  {
    return (EReference)entityReferenceFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEntityReferenceField_LowerBound()
  {
    return (EAttribute)entityReferenceFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEntityReferenceField_UpperBound()
  {
    return (EAttribute)entityReferenceFieldEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityReferenceField_Opposite()
  {
    return (EReference)entityReferenceFieldEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityReferenceField_Attrs()
  {
    return (EReference)entityReferenceFieldEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityReferenceFieldAttr()
  {
    return entityReferenceFieldAttrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityReferenceFieldAttr_Glossary()
  {
    return (EReference)entityReferenceFieldAttrEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityReferenceFieldAttr_Widget()
  {
    return (EReference)entityReferenceFieldAttrEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityReferenceFieldAttr_Constraint()
  {
    return (EReference)entityReferenceFieldAttrEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityReferenceFieldAttr_Db_map()
  {
    return (EReference)entityReferenceFieldAttrEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityReferenceFieldAttr_Data_domain()
  {
    return (EReference)entityReferenceFieldAttrEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityReferenceFieldAttr_Business_rule()
  {
    return (EReference)entityReferenceFieldAttrEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEnumEntity()
  {
    return enumEntityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityImageField()
  {
    return entityImageFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityImageField_Attrs()
  {
    return (EReference)entityImageFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityFileField()
  {
    return entityFileFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityFileField_Attrs()
  {
    return (EReference)entityFileFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityEmailField()
  {
    return entityEmailFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityEmailField_Attrs()
  {
    return (EReference)entityEmailFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityDecimalField()
  {
    return entityDecimalFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityDecimalField_Attrs()
  {
    return (EReference)entityDecimalFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityIntegerField()
  {
    return entityIntegerFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityIntegerField_Attrs()
  {
    return (EReference)entityIntegerFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityCurrencyField()
  {
    return entityCurrencyFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityCurrencyField_Attrs()
  {
    return (EReference)entityCurrencyFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityAttr()
  {
    return entityAttrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityAttr_Glossary()
  {
    return (EReference)entityAttrEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityAttr_Widget()
  {
    return (EReference)entityAttrEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityAttr_Constraint()
  {
    return (EReference)entityAttrEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityAttr_Db_map()
  {
    return (EReference)entityAttrEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityAttr_Data_domain()
  {
    return (EReference)entityAttrEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityAttr_Business_rule()
  {
    return (EReference)entityAttrEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConstraintRequired()
  {
    return constraintRequiredEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConstraintRequired_Value()
  {
    return (EAttribute)constraintRequiredEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConstraintUnique()
  {
    return constraintUniqueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConstraintUnique_Value()
  {
    return (EAttribute)constraintUniqueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConstraintMaxLength()
  {
    return constraintMaxLengthEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConstraintMaxLength_Value()
  {
    return (EAttribute)constraintMaxLengthEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConstraintMinLength()
  {
    return constraintMinLengthEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConstraintMinLength_Value()
  {
    return (EAttribute)constraintMinLengthEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGlossary()
  {
    return glossaryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getGlossary_Glossary_name()
  {
    return (EReference)glossaryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getGlossary_Glossary_description()
  {
    return (EReference)glossaryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGlossaryName()
  {
    return glossaryNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGlossaryName_Label()
  {
    return (EAttribute)glossaryNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGlossaryDescription()
  {
    return glossaryDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGlossaryDescription_Label()
  {
    return (EAttribute)glossaryDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetLabel()
  {
    return widgetLabelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetLabel_Label()
  {
    return (EAttribute)widgetLabelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetHelp()
  {
    return widgetHelpEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetHelp_Help()
  {
    return (EAttribute)widgetHelpEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetExposedFilter()
  {
    return widgetExposedFilterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetExposedFilter_Exposed_filter()
  {
    return (EAttribute)widgetExposedFilterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetType()
  {
    return widgetTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetType_Type()
  {
    return (EAttribute)widgetTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetTypeSelect()
  {
    return widgetTypeSelectEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetTypeSelect_Type()
  {
    return (EAttribute)widgetTypeSelectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWidgetTypeSelect_Sortby()
  {
    return (EReference)widgetTypeSelectEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetSortBy()
  {
    return widgetSortByEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetSortBy_Sortby()
  {
    return (EAttribute)widgetSortByEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetStartYear()
  {
    return widgetStartYearEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetStartYear_Start()
  {
    return (EAttribute)widgetStartYearEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetEndYear()
  {
    return widgetEndYearEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetEndYear_End()
  {
    return (EAttribute)widgetEndYearEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidget()
  {
    return widgetEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidget_Widget()
  {
    return (EAttribute)widgetEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWidget_Attrs()
  {
    return (EReference)widgetEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetEnum()
  {
    return widgetEnumEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetEnum_Widget()
  {
    return (EAttribute)widgetEnumEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWidgetEnum_Attrs()
  {
    return (EReference)widgetEnumEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetDate()
  {
    return widgetDateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetDate_Widget()
  {
    return (EAttribute)widgetDateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWidgetDate_Attrs()
  {
    return (EReference)widgetDateEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetText()
  {
    return widgetTextEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetText_Widget()
  {
    return (EAttribute)widgetTextEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWidgetText_Attrs()
  {
    return (EReference)widgetTextEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetAttr()
  {
    return widgetAttrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetAttrEnum()
  {
    return widgetAttrEnumEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetAttrEnumType()
  {
    return widgetAttrEnumTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetAttrEnumTypeSelect()
  {
    return widgetAttrEnumTypeSelectEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetAttrDate()
  {
    return widgetAttrDateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetAttrText()
  {
    return widgetAttrTextEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetSize()
  {
    return widgetSizeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetSize_Type()
  {
    return (EAttribute)widgetSizeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWidgetDisplayResult()
  {
    return widgetDisplayResultEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWidgetDisplayResult_Display_result()
  {
    return (EAttribute)widgetDisplayResultEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDATE()
  {
    return dateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDATE_Date()
  {
    return (EAttribute)dateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDATE_Now()
  {
    return (EAttribute)dateEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getActionSearch()
  {
    return actionSearchEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getActionAdd()
  {
    return actionAddEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getActionEdit()
  {
    return actionEditEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getActionDelete()
  {
    return actionDeleteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAction()
  {
    return actionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAction_Value()
  {
    return (EAttribute)actionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getActions()
  {
    return actionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getActions_Action()
  {
    return (EReference)actionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDBMapEntity()
  {
    return dbMapEntityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDBMapEntity_Table()
  {
    return (EAttribute)dbMapEntityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDBMapEntity_Dbmap_attrs()
  {
    return (EReference)dbMapEntityEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDBMapAttr()
  {
    return dbMapAttrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDBMapAttrIdentity()
  {
    return dbMapAttrIdentityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDBMapAttrIdentity_Identity()
  {
    return (EAttribute)dbMapAttrIdentityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDBMapAttrAutoId()
  {
    return dbMapAttrAutoIdEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDBMapAttrAutoId_Autoid()
  {
    return (EAttribute)dbMapAttrAutoIdEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDBMapField()
  {
    return dbMapFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDBMapField_Table()
  {
    return (EAttribute)dbMapFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDBMapField_Pk()
  {
    return (EAttribute)dbMapFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDataDomain()
  {
    return dataDomainEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDataDomain_Domain()
  {
    return (EAttribute)dataDomainEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBusinessRule()
  {
    return businessRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBusinessRule_Code()
  {
    return (EAttribute)businessRuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBusinessRule_Description()
  {
    return (EAttribute)businessRuleEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RdlFactory getRdlFactory()
  {
    return (RdlFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__MODULE);

    moduleEClass = createEClass(MODULE);
    createEAttribute(moduleEClass, MODULE__NAME);
    createEReference(moduleEClass, MODULE__ELEMENTS);

    abstractElementEClass = createEClass(ABSTRACT_ELEMENT);

    enumEClass = createEClass(ENUM);
    createEAttribute(enumEClass, ENUM__NAME);
    createEReference(enumEClass, ENUM__ENUM_LITERALS);

    enumLiteralEClass = createEClass(ENUM_LITERAL);
    createEAttribute(enumLiteralEClass, ENUM_LITERAL__KEY);
    createEAttribute(enumLiteralEClass, ENUM_LITERAL__VALUE);

    entityEClass = createEClass(ENTITY);
    createEAttribute(entityEClass, ENTITY__NAME);
    createEReference(entityEClass, ENTITY__ACTIONS);
    createEReference(entityEClass, ENTITY__GLOSSARY);
    createEReference(entityEClass, ENTITY__DB_MAP);
    createEReference(entityEClass, ENTITY__ENTITY_FIELDS);
    createEReference(entityEClass, ENTITY__ENTITY_METHODS);

    methodDeclarationEClass = createEClass(METHOD_DECLARATION);
    createEAttribute(methodDeclarationEClass, METHOD_DECLARATION__NAME);
    createEReference(methodDeclarationEClass, METHOD_DECLARATION__DEF_STATEMENTS);

    statementEClass = createEClass(STATEMENT);

    statementReturnEClass = createEClass(STATEMENT_RETURN);
    createEReference(statementReturnEClass, STATEMENT_RETURN__ENTITYFIELD);

    entityFieldEClass = createEClass(ENTITY_FIELD);
    createEAttribute(entityFieldEClass, ENTITY_FIELD__NAME);

    entityTextConstraintDefEClass = createEClass(ENTITY_TEXT_CONSTRAINT_DEF);
    createEReference(entityTextConstraintDefEClass, ENTITY_TEXT_CONSTRAINT_DEF__CONSTRAINTS);

    entityTextConstraintEClass = createEClass(ENTITY_TEXT_CONSTRAINT);

    entityTextFieldEClass = createEClass(ENTITY_TEXT_FIELD);
    createEReference(entityTextFieldEClass, ENTITY_TEXT_FIELD__ATTRS);

    entityTextFieldAttrEClass = createEClass(ENTITY_TEXT_FIELD_ATTR);
    createEReference(entityTextFieldAttrEClass, ENTITY_TEXT_FIELD_ATTR__GLOSSARY);
    createEReference(entityTextFieldAttrEClass, ENTITY_TEXT_FIELD_ATTR__WIDGET);
    createEReference(entityTextFieldAttrEClass, ENTITY_TEXT_FIELD_ATTR__CONSTRAINT);
    createEReference(entityTextFieldAttrEClass, ENTITY_TEXT_FIELD_ATTR__DB_MAP);
    createEReference(entityTextFieldAttrEClass, ENTITY_TEXT_FIELD_ATTR__DATA_DOMAIN);
    createEReference(entityTextFieldAttrEClass, ENTITY_TEXT_FIELD_ATTR__BUSINESS_RULE);

    entityLongTextFieldEClass = createEClass(ENTITY_LONG_TEXT_FIELD);
    createEReference(entityLongTextFieldEClass, ENTITY_LONG_TEXT_FIELD__ATTRS);

    entityLongTextFieldAttrEClass = createEClass(ENTITY_LONG_TEXT_FIELD_ATTR);
    createEReference(entityLongTextFieldAttrEClass, ENTITY_LONG_TEXT_FIELD_ATTR__GLOSSARY);
    createEReference(entityLongTextFieldAttrEClass, ENTITY_LONG_TEXT_FIELD_ATTR__WIDGET);
    createEReference(entityLongTextFieldAttrEClass, ENTITY_LONG_TEXT_FIELD_ATTR__CONSTRAINT);
    createEReference(entityLongTextFieldAttrEClass, ENTITY_LONG_TEXT_FIELD_ATTR__DB_MAP);
    createEReference(entityLongTextFieldAttrEClass, ENTITY_LONG_TEXT_FIELD_ATTR__DATA_DOMAIN);
    createEReference(entityLongTextFieldAttrEClass, ENTITY_LONG_TEXT_FIELD_ATTR__BUSINESS_RULE);

    entityDateFieldEClass = createEClass(ENTITY_DATE_FIELD);
    createEReference(entityDateFieldEClass, ENTITY_DATE_FIELD__ATTRS);

    entityDateFieldAttrEClass = createEClass(ENTITY_DATE_FIELD_ATTR);
    createEReference(entityDateFieldAttrEClass, ENTITY_DATE_FIELD_ATTR__DEFAULT);
    createEReference(entityDateFieldAttrEClass, ENTITY_DATE_FIELD_ATTR__GLOSSARY);
    createEReference(entityDateFieldAttrEClass, ENTITY_DATE_FIELD_ATTR__WIDGET);
    createEReference(entityDateFieldAttrEClass, ENTITY_DATE_FIELD_ATTR__CONSTRAINT);
    createEReference(entityDateFieldAttrEClass, ENTITY_DATE_FIELD_ATTR__DB_MAP);
    createEReference(entityDateFieldAttrEClass, ENTITY_DATE_FIELD_ATTR__DATA_DOMAIN);
    createEReference(entityDateFieldAttrEClass, ENTITY_DATE_FIELD_ATTR__BUSINESS_RULE);

    entityReferenceFieldEClass = createEClass(ENTITY_REFERENCE_FIELD);
    createEReference(entityReferenceFieldEClass, ENTITY_REFERENCE_FIELD__SUPER_TYPE);
    createEAttribute(entityReferenceFieldEClass, ENTITY_REFERENCE_FIELD__LOWER_BOUND);
    createEAttribute(entityReferenceFieldEClass, ENTITY_REFERENCE_FIELD__UPPER_BOUND);
    createEReference(entityReferenceFieldEClass, ENTITY_REFERENCE_FIELD__OPPOSITE);
    createEReference(entityReferenceFieldEClass, ENTITY_REFERENCE_FIELD__ATTRS);

    entityReferenceFieldAttrEClass = createEClass(ENTITY_REFERENCE_FIELD_ATTR);
    createEReference(entityReferenceFieldAttrEClass, ENTITY_REFERENCE_FIELD_ATTR__GLOSSARY);
    createEReference(entityReferenceFieldAttrEClass, ENTITY_REFERENCE_FIELD_ATTR__WIDGET);
    createEReference(entityReferenceFieldAttrEClass, ENTITY_REFERENCE_FIELD_ATTR__CONSTRAINT);
    createEReference(entityReferenceFieldAttrEClass, ENTITY_REFERENCE_FIELD_ATTR__DB_MAP);
    createEReference(entityReferenceFieldAttrEClass, ENTITY_REFERENCE_FIELD_ATTR__DATA_DOMAIN);
    createEReference(entityReferenceFieldAttrEClass, ENTITY_REFERENCE_FIELD_ATTR__BUSINESS_RULE);

    enumEntityEClass = createEClass(ENUM_ENTITY);

    entityImageFieldEClass = createEClass(ENTITY_IMAGE_FIELD);
    createEReference(entityImageFieldEClass, ENTITY_IMAGE_FIELD__ATTRS);

    entityFileFieldEClass = createEClass(ENTITY_FILE_FIELD);
    createEReference(entityFileFieldEClass, ENTITY_FILE_FIELD__ATTRS);

    entityEmailFieldEClass = createEClass(ENTITY_EMAIL_FIELD);
    createEReference(entityEmailFieldEClass, ENTITY_EMAIL_FIELD__ATTRS);

    entityDecimalFieldEClass = createEClass(ENTITY_DECIMAL_FIELD);
    createEReference(entityDecimalFieldEClass, ENTITY_DECIMAL_FIELD__ATTRS);

    entityIntegerFieldEClass = createEClass(ENTITY_INTEGER_FIELD);
    createEReference(entityIntegerFieldEClass, ENTITY_INTEGER_FIELD__ATTRS);

    entityCurrencyFieldEClass = createEClass(ENTITY_CURRENCY_FIELD);
    createEReference(entityCurrencyFieldEClass, ENTITY_CURRENCY_FIELD__ATTRS);

    entityAttrEClass = createEClass(ENTITY_ATTR);
    createEReference(entityAttrEClass, ENTITY_ATTR__GLOSSARY);
    createEReference(entityAttrEClass, ENTITY_ATTR__WIDGET);
    createEReference(entityAttrEClass, ENTITY_ATTR__CONSTRAINT);
    createEReference(entityAttrEClass, ENTITY_ATTR__DB_MAP);
    createEReference(entityAttrEClass, ENTITY_ATTR__DATA_DOMAIN);
    createEReference(entityAttrEClass, ENTITY_ATTR__BUSINESS_RULE);

    constraintRequiredEClass = createEClass(CONSTRAINT_REQUIRED);
    createEAttribute(constraintRequiredEClass, CONSTRAINT_REQUIRED__VALUE);

    constraintUniqueEClass = createEClass(CONSTRAINT_UNIQUE);
    createEAttribute(constraintUniqueEClass, CONSTRAINT_UNIQUE__VALUE);

    constraintMaxLengthEClass = createEClass(CONSTRAINT_MAX_LENGTH);
    createEAttribute(constraintMaxLengthEClass, CONSTRAINT_MAX_LENGTH__VALUE);

    constraintMinLengthEClass = createEClass(CONSTRAINT_MIN_LENGTH);
    createEAttribute(constraintMinLengthEClass, CONSTRAINT_MIN_LENGTH__VALUE);

    glossaryEClass = createEClass(GLOSSARY);
    createEReference(glossaryEClass, GLOSSARY__GLOSSARY_NAME);
    createEReference(glossaryEClass, GLOSSARY__GLOSSARY_DESCRIPTION);

    glossaryNameEClass = createEClass(GLOSSARY_NAME);
    createEAttribute(glossaryNameEClass, GLOSSARY_NAME__LABEL);

    glossaryDescriptionEClass = createEClass(GLOSSARY_DESCRIPTION);
    createEAttribute(glossaryDescriptionEClass, GLOSSARY_DESCRIPTION__LABEL);

    widgetLabelEClass = createEClass(WIDGET_LABEL);
    createEAttribute(widgetLabelEClass, WIDGET_LABEL__LABEL);

    widgetHelpEClass = createEClass(WIDGET_HELP);
    createEAttribute(widgetHelpEClass, WIDGET_HELP__HELP);

    widgetExposedFilterEClass = createEClass(WIDGET_EXPOSED_FILTER);
    createEAttribute(widgetExposedFilterEClass, WIDGET_EXPOSED_FILTER__EXPOSED_FILTER);

    widgetTypeEClass = createEClass(WIDGET_TYPE);
    createEAttribute(widgetTypeEClass, WIDGET_TYPE__TYPE);

    widgetTypeSelectEClass = createEClass(WIDGET_TYPE_SELECT);
    createEAttribute(widgetTypeSelectEClass, WIDGET_TYPE_SELECT__TYPE);
    createEReference(widgetTypeSelectEClass, WIDGET_TYPE_SELECT__SORTBY);

    widgetSortByEClass = createEClass(WIDGET_SORT_BY);
    createEAttribute(widgetSortByEClass, WIDGET_SORT_BY__SORTBY);

    widgetStartYearEClass = createEClass(WIDGET_START_YEAR);
    createEAttribute(widgetStartYearEClass, WIDGET_START_YEAR__START);

    widgetEndYearEClass = createEClass(WIDGET_END_YEAR);
    createEAttribute(widgetEndYearEClass, WIDGET_END_YEAR__END);

    widgetEClass = createEClass(WIDGET);
    createEAttribute(widgetEClass, WIDGET__WIDGET);
    createEReference(widgetEClass, WIDGET__ATTRS);

    widgetEnumEClass = createEClass(WIDGET_ENUM);
    createEAttribute(widgetEnumEClass, WIDGET_ENUM__WIDGET);
    createEReference(widgetEnumEClass, WIDGET_ENUM__ATTRS);

    widgetDateEClass = createEClass(WIDGET_DATE);
    createEAttribute(widgetDateEClass, WIDGET_DATE__WIDGET);
    createEReference(widgetDateEClass, WIDGET_DATE__ATTRS);

    widgetTextEClass = createEClass(WIDGET_TEXT);
    createEAttribute(widgetTextEClass, WIDGET_TEXT__WIDGET);
    createEReference(widgetTextEClass, WIDGET_TEXT__ATTRS);

    widgetAttrEClass = createEClass(WIDGET_ATTR);

    widgetAttrEnumEClass = createEClass(WIDGET_ATTR_ENUM);

    widgetAttrEnumTypeEClass = createEClass(WIDGET_ATTR_ENUM_TYPE);

    widgetAttrEnumTypeSelectEClass = createEClass(WIDGET_ATTR_ENUM_TYPE_SELECT);

    widgetAttrDateEClass = createEClass(WIDGET_ATTR_DATE);

    widgetAttrTextEClass = createEClass(WIDGET_ATTR_TEXT);

    widgetSizeEClass = createEClass(WIDGET_SIZE);
    createEAttribute(widgetSizeEClass, WIDGET_SIZE__TYPE);

    widgetDisplayResultEClass = createEClass(WIDGET_DISPLAY_RESULT);
    createEAttribute(widgetDisplayResultEClass, WIDGET_DISPLAY_RESULT__DISPLAY_RESULT);

    dateEClass = createEClass(DATE);
    createEAttribute(dateEClass, DATE__DATE);
    createEAttribute(dateEClass, DATE__NOW);

    actionSearchEClass = createEClass(ACTION_SEARCH);

    actionAddEClass = createEClass(ACTION_ADD);

    actionEditEClass = createEClass(ACTION_EDIT);

    actionDeleteEClass = createEClass(ACTION_DELETE);

    actionEClass = createEClass(ACTION);
    createEAttribute(actionEClass, ACTION__VALUE);

    actionsEClass = createEClass(ACTIONS);
    createEReference(actionsEClass, ACTIONS__ACTION);

    dbMapEntityEClass = createEClass(DB_MAP_ENTITY);
    createEAttribute(dbMapEntityEClass, DB_MAP_ENTITY__TABLE);
    createEReference(dbMapEntityEClass, DB_MAP_ENTITY__DBMAP_ATTRS);

    dbMapAttrEClass = createEClass(DB_MAP_ATTR);

    dbMapAttrIdentityEClass = createEClass(DB_MAP_ATTR_IDENTITY);
    createEAttribute(dbMapAttrIdentityEClass, DB_MAP_ATTR_IDENTITY__IDENTITY);

    dbMapAttrAutoIdEClass = createEClass(DB_MAP_ATTR_AUTO_ID);
    createEAttribute(dbMapAttrAutoIdEClass, DB_MAP_ATTR_AUTO_ID__AUTOID);

    dbMapFieldEClass = createEClass(DB_MAP_FIELD);
    createEAttribute(dbMapFieldEClass, DB_MAP_FIELD__TABLE);
    createEAttribute(dbMapFieldEClass, DB_MAP_FIELD__PK);

    dataDomainEClass = createEClass(DATA_DOMAIN);
    createEAttribute(dataDomainEClass, DATA_DOMAIN__DOMAIN);

    businessRuleEClass = createEClass(BUSINESS_RULE);
    createEAttribute(businessRuleEClass, BUSINESS_RULE__CODE);
    createEAttribute(businessRuleEClass, BUSINESS_RULE__DESCRIPTION);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    enumEClass.getESuperTypes().add(this.getAbstractElement());
    enumEClass.getESuperTypes().add(this.getEnumEntity());
    entityEClass.getESuperTypes().add(this.getAbstractElement());
    entityEClass.getESuperTypes().add(this.getEnumEntity());
    statementReturnEClass.getESuperTypes().add(this.getStatement());
    entityTextFieldEClass.getESuperTypes().add(this.getEntityField());
    entityLongTextFieldEClass.getESuperTypes().add(this.getEntityField());
    entityDateFieldEClass.getESuperTypes().add(this.getEntityField());
    entityReferenceFieldEClass.getESuperTypes().add(this.getEntityField());
    entityImageFieldEClass.getESuperTypes().add(this.getEntityField());
    entityFileFieldEClass.getESuperTypes().add(this.getEntityField());
    entityEmailFieldEClass.getESuperTypes().add(this.getEntityField());
    entityDecimalFieldEClass.getESuperTypes().add(this.getEntityField());
    entityIntegerFieldEClass.getESuperTypes().add(this.getEntityField());
    entityCurrencyFieldEClass.getESuperTypes().add(this.getEntityField());
    constraintRequiredEClass.getESuperTypes().add(this.getEntityTextConstraint());
    constraintUniqueEClass.getESuperTypes().add(this.getEntityTextConstraint());
    constraintMaxLengthEClass.getESuperTypes().add(this.getEntityTextConstraint());
    constraintMinLengthEClass.getESuperTypes().add(this.getEntityTextConstraint());
    widgetLabelEClass.getESuperTypes().add(this.getWidgetAttr());
    widgetLabelEClass.getESuperTypes().add(this.getWidgetAttrEnumType());
    widgetLabelEClass.getESuperTypes().add(this.getWidgetAttrDate());
    widgetLabelEClass.getESuperTypes().add(this.getWidgetAttrText());
    widgetHelpEClass.getESuperTypes().add(this.getWidgetAttr());
    widgetHelpEClass.getESuperTypes().add(this.getWidgetAttrEnumType());
    widgetHelpEClass.getESuperTypes().add(this.getWidgetAttrDate());
    widgetHelpEClass.getESuperTypes().add(this.getWidgetAttrText());
    widgetExposedFilterEClass.getESuperTypes().add(this.getWidgetAttr());
    widgetExposedFilterEClass.getESuperTypes().add(this.getWidgetAttrEnumType());
    widgetExposedFilterEClass.getESuperTypes().add(this.getWidgetAttrDate());
    widgetExposedFilterEClass.getESuperTypes().add(this.getWidgetAttrText());
    widgetTypeEClass.getESuperTypes().add(this.getWidgetAttrEnumType());
    widgetTypeSelectEClass.getESuperTypes().add(this.getWidgetAttrEnumTypeSelect());
    widgetStartYearEClass.getESuperTypes().add(this.getWidgetAttrDate());
    widgetEndYearEClass.getESuperTypes().add(this.getWidgetAttrDate());
    widgetAttrEnumTypeEClass.getESuperTypes().add(this.getWidgetAttrEnum());
    widgetAttrEnumTypeSelectEClass.getESuperTypes().add(this.getWidgetAttrEnum());
    widgetSizeEClass.getESuperTypes().add(this.getWidgetAttrText());
    widgetDisplayResultEClass.getESuperTypes().add(this.getWidgetAttr());
    widgetDisplayResultEClass.getESuperTypes().add(this.getWidgetAttrEnum());
    widgetDisplayResultEClass.getESuperTypes().add(this.getWidgetAttrDate());
    widgetDisplayResultEClass.getESuperTypes().add(this.getWidgetAttrText());
    actionSearchEClass.getESuperTypes().add(this.getAction());
    actionAddEClass.getESuperTypes().add(this.getAction());
    actionEditEClass.getESuperTypes().add(this.getAction());
    actionDeleteEClass.getESuperTypes().add(this.getAction());
    dbMapAttrIdentityEClass.getESuperTypes().add(this.getDBMapAttr());
    dbMapAttrAutoIdEClass.getESuperTypes().add(this.getDBMapAttr());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Module(), this.getModule(), null, "module", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(moduleEClass, Module.class, "Module", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getModule_Name(), ecorePackage.getEString(), "name", null, 0, 1, Module.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModule_Elements(), this.getAbstractElement(), null, "elements", null, 0, -1, Module.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(abstractElementEClass, AbstractElement.class, "AbstractElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(enumEClass, com.softtek.rdl.Enum.class, "Enum", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEnum_Name(), ecorePackage.getEString(), "name", null, 0, 1, com.softtek.rdl.Enum.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEnum_Enum_literals(), this.getEnumLiteral(), null, "enum_literals", null, 0, -1, com.softtek.rdl.Enum.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(enumLiteralEClass, EnumLiteral.class, "EnumLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEnumLiteral_Key(), ecorePackage.getEString(), "key", null, 0, 1, EnumLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnumLiteral_Value(), ecorePackage.getEString(), "value", null, 0, 1, EnumLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityEClass, Entity.class, "Entity", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEntity_Name(), ecorePackage.getEString(), "name", null, 0, 1, Entity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntity_Actions(), this.getActions(), null, "actions", null, 0, 1, Entity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntity_Glossary(), this.getGlossary(), null, "glossary", null, 0, 1, Entity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntity_Db_map(), this.getDBMapEntity(), null, "db_map", null, 0, 1, Entity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntity_Entity_fields(), this.getEntityField(), null, "entity_fields", null, 0, -1, Entity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntity_Entity_methods(), this.getMethodDeclaration(), null, "entity_methods", null, 0, -1, Entity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(methodDeclarationEClass, MethodDeclaration.class, "MethodDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMethodDeclaration_Name(), ecorePackage.getEString(), "name", null, 0, 1, MethodDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMethodDeclaration_Def_statements(), this.getStatement(), null, "def_statements", null, 0, -1, MethodDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(statementEClass, Statement.class, "Statement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(statementReturnEClass, StatementReturn.class, "StatementReturn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStatementReturn_Entityfield(), this.getEntityField(), null, "entityfield", null, 0, 1, StatementReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityFieldEClass, EntityField.class, "EntityField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEntityField_Name(), ecorePackage.getEString(), "name", null, 0, 1, EntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityTextConstraintDefEClass, EntityTextConstraintDef.class, "EntityTextConstraintDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityTextConstraintDef_Constraints(), this.getEntityTextConstraint(), null, "constraints", null, 0, -1, EntityTextConstraintDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityTextConstraintEClass, EntityTextConstraint.class, "EntityTextConstraint", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(entityTextFieldEClass, EntityTextField.class, "EntityTextField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityTextField_Attrs(), this.getEntityTextFieldAttr(), null, "attrs", null, 0, -1, EntityTextField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityTextFieldAttrEClass, EntityTextFieldAttr.class, "EntityTextFieldAttr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityTextFieldAttr_Glossary(), this.getGlossary(), null, "glossary", null, 0, 1, EntityTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityTextFieldAttr_Widget(), this.getWidgetText(), null, "widget", null, 0, 1, EntityTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityTextFieldAttr_Constraint(), this.getEntityTextConstraintDef(), null, "constraint", null, 0, 1, EntityTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityTextFieldAttr_Db_map(), this.getDBMapField(), null, "db_map", null, 0, 1, EntityTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityTextFieldAttr_Data_domain(), this.getDataDomain(), null, "data_domain", null, 0, 1, EntityTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityTextFieldAttr_Business_rule(), this.getBusinessRule(), null, "business_rule", null, 0, 1, EntityTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityLongTextFieldEClass, EntityLongTextField.class, "EntityLongTextField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityLongTextField_Attrs(), this.getEntityLongTextFieldAttr(), null, "attrs", null, 0, -1, EntityLongTextField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityLongTextFieldAttrEClass, EntityLongTextFieldAttr.class, "EntityLongTextFieldAttr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityLongTextFieldAttr_Glossary(), this.getGlossary(), null, "glossary", null, 0, 1, EntityLongTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityLongTextFieldAttr_Widget(), this.getWidget(), null, "widget", null, 0, 1, EntityLongTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityLongTextFieldAttr_Constraint(), this.getEntityTextConstraintDef(), null, "constraint", null, 0, 1, EntityLongTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityLongTextFieldAttr_Db_map(), this.getDBMapField(), null, "db_map", null, 0, 1, EntityLongTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityLongTextFieldAttr_Data_domain(), this.getDataDomain(), null, "data_domain", null, 0, 1, EntityLongTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityLongTextFieldAttr_Business_rule(), this.getBusinessRule(), null, "business_rule", null, 0, 1, EntityLongTextFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityDateFieldEClass, EntityDateField.class, "EntityDateField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityDateField_Attrs(), this.getEntityDateFieldAttr(), null, "attrs", null, 0, -1, EntityDateField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityDateFieldAttrEClass, EntityDateFieldAttr.class, "EntityDateFieldAttr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityDateFieldAttr_Default(), this.getDATE(), null, "default", null, 0, 1, EntityDateFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityDateFieldAttr_Glossary(), this.getGlossary(), null, "glossary", null, 0, 1, EntityDateFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityDateFieldAttr_Widget(), this.getWidgetDate(), null, "widget", null, 0, 1, EntityDateFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityDateFieldAttr_Constraint(), this.getEntityTextConstraintDef(), null, "constraint", null, 0, 1, EntityDateFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityDateFieldAttr_Db_map(), this.getDBMapField(), null, "db_map", null, 0, 1, EntityDateFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityDateFieldAttr_Data_domain(), this.getDataDomain(), null, "data_domain", null, 0, 1, EntityDateFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityDateFieldAttr_Business_rule(), this.getBusinessRule(), null, "business_rule", null, 0, 1, EntityDateFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityReferenceFieldEClass, EntityReferenceField.class, "EntityReferenceField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityReferenceField_SuperType(), this.getEnumEntity(), null, "superType", null, 0, 1, EntityReferenceField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEntityReferenceField_LowerBound(), ecorePackage.getEInt(), "lowerBound", null, 0, 1, EntityReferenceField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEntityReferenceField_UpperBound(), ecorePackage.getEString(), "upperBound", null, 0, 1, EntityReferenceField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityReferenceField_Opposite(), this.getEntityReferenceField(), null, "opposite", null, 0, 1, EntityReferenceField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityReferenceField_Attrs(), this.getEntityReferenceFieldAttr(), null, "attrs", null, 0, -1, EntityReferenceField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityReferenceFieldAttrEClass, EntityReferenceFieldAttr.class, "EntityReferenceFieldAttr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityReferenceFieldAttr_Glossary(), this.getGlossary(), null, "glossary", null, 0, 1, EntityReferenceFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityReferenceFieldAttr_Widget(), this.getWidgetEnum(), null, "widget", null, 0, 1, EntityReferenceFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityReferenceFieldAttr_Constraint(), this.getEntityTextConstraintDef(), null, "constraint", null, 0, 1, EntityReferenceFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityReferenceFieldAttr_Db_map(), this.getDBMapField(), null, "db_map", null, 0, 1, EntityReferenceFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityReferenceFieldAttr_Data_domain(), this.getDataDomain(), null, "data_domain", null, 0, 1, EntityReferenceFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityReferenceFieldAttr_Business_rule(), this.getBusinessRule(), null, "business_rule", null, 0, 1, EntityReferenceFieldAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(enumEntityEClass, EnumEntity.class, "EnumEntity", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(entityImageFieldEClass, EntityImageField.class, "EntityImageField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityImageField_Attrs(), this.getEntityAttr(), null, "attrs", null, 0, -1, EntityImageField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityFileFieldEClass, EntityFileField.class, "EntityFileField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityFileField_Attrs(), this.getEntityAttr(), null, "attrs", null, 0, -1, EntityFileField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityEmailFieldEClass, EntityEmailField.class, "EntityEmailField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityEmailField_Attrs(), this.getEntityAttr(), null, "attrs", null, 0, -1, EntityEmailField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityDecimalFieldEClass, EntityDecimalField.class, "EntityDecimalField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityDecimalField_Attrs(), this.getEntityAttr(), null, "attrs", null, 0, -1, EntityDecimalField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityIntegerFieldEClass, EntityIntegerField.class, "EntityIntegerField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityIntegerField_Attrs(), this.getEntityAttr(), null, "attrs", null, 0, -1, EntityIntegerField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityCurrencyFieldEClass, EntityCurrencyField.class, "EntityCurrencyField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityCurrencyField_Attrs(), this.getEntityAttr(), null, "attrs", null, 0, -1, EntityCurrencyField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityAttrEClass, EntityAttr.class, "EntityAttr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityAttr_Glossary(), this.getGlossary(), null, "glossary", null, 0, 1, EntityAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityAttr_Widget(), this.getWidget(), null, "widget", null, 0, 1, EntityAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityAttr_Constraint(), this.getEntityTextConstraintDef(), null, "constraint", null, 0, 1, EntityAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityAttr_Db_map(), this.getDBMapField(), null, "db_map", null, 0, 1, EntityAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityAttr_Data_domain(), this.getDataDomain(), null, "data_domain", null, 0, 1, EntityAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityAttr_Business_rule(), this.getBusinessRule(), null, "business_rule", null, 0, 1, EntityAttr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constraintRequiredEClass, ConstraintRequired.class, "ConstraintRequired", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstraintRequired_Value(), ecorePackage.getEString(), "value", null, 0, 1, ConstraintRequired.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constraintUniqueEClass, ConstraintUnique.class, "ConstraintUnique", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstraintUnique_Value(), ecorePackage.getEString(), "value", null, 0, 1, ConstraintUnique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constraintMaxLengthEClass, ConstraintMaxLength.class, "ConstraintMaxLength", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstraintMaxLength_Value(), ecorePackage.getEInt(), "value", null, 0, 1, ConstraintMaxLength.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constraintMinLengthEClass, ConstraintMinLength.class, "ConstraintMinLength", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstraintMinLength_Value(), ecorePackage.getEInt(), "value", null, 0, 1, ConstraintMinLength.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(glossaryEClass, Glossary.class, "Glossary", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGlossary_Glossary_name(), this.getGlossaryName(), null, "glossary_name", null, 0, 1, Glossary.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGlossary_Glossary_description(), this.getGlossaryDescription(), null, "glossary_description", null, 0, 1, Glossary.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(glossaryNameEClass, GlossaryName.class, "GlossaryName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGlossaryName_Label(), ecorePackage.getEString(), "label", null, 0, 1, GlossaryName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(glossaryDescriptionEClass, GlossaryDescription.class, "GlossaryDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGlossaryDescription_Label(), ecorePackage.getEString(), "label", null, 0, 1, GlossaryDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetLabelEClass, WidgetLabel.class, "WidgetLabel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetLabel_Label(), ecorePackage.getEString(), "label", null, 0, 1, WidgetLabel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetHelpEClass, WidgetHelp.class, "WidgetHelp", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetHelp_Help(), ecorePackage.getEString(), "help", null, 0, 1, WidgetHelp.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetExposedFilterEClass, WidgetExposedFilter.class, "WidgetExposedFilter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetExposedFilter_Exposed_filter(), ecorePackage.getEString(), "exposed_filter", null, 0, 1, WidgetExposedFilter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetTypeEClass, WidgetType.class, "WidgetType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetType_Type(), ecorePackage.getEString(), "type", null, 0, 1, WidgetType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetTypeSelectEClass, WidgetTypeSelect.class, "WidgetTypeSelect", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetTypeSelect_Type(), ecorePackage.getEString(), "type", null, 0, 1, WidgetTypeSelect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getWidgetTypeSelect_Sortby(), this.getWidgetSortBy(), null, "sortby", null, 0, 1, WidgetTypeSelect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetSortByEClass, WidgetSortBy.class, "WidgetSortBy", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetSortBy_Sortby(), ecorePackage.getEString(), "sortby", null, 0, 1, WidgetSortBy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetStartYearEClass, WidgetStartYear.class, "WidgetStartYear", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetStartYear_Start(), ecorePackage.getEString(), "start", null, 0, 1, WidgetStartYear.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetEndYearEClass, WidgetEndYear.class, "WidgetEndYear", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetEndYear_End(), ecorePackage.getEString(), "end", null, 0, 1, WidgetEndYear.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetEClass, Widget.class, "Widget", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidget_Widget(), ecorePackage.getEString(), "widget", null, 0, 1, Widget.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getWidget_Attrs(), this.getWidgetAttr(), null, "attrs", null, 0, -1, Widget.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetEnumEClass, WidgetEnum.class, "WidgetEnum", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetEnum_Widget(), ecorePackage.getEString(), "widget", null, 0, 1, WidgetEnum.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getWidgetEnum_Attrs(), this.getWidgetAttrEnum(), null, "attrs", null, 0, -1, WidgetEnum.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetDateEClass, WidgetDate.class, "WidgetDate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetDate_Widget(), ecorePackage.getEString(), "widget", null, 0, 1, WidgetDate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getWidgetDate_Attrs(), this.getWidgetAttrDate(), null, "attrs", null, 0, -1, WidgetDate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetTextEClass, WidgetText.class, "WidgetText", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetText_Widget(), ecorePackage.getEString(), "widget", null, 0, 1, WidgetText.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getWidgetText_Attrs(), this.getWidgetAttrText(), null, "attrs", null, 0, -1, WidgetText.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetAttrEClass, WidgetAttr.class, "WidgetAttr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(widgetAttrEnumEClass, WidgetAttrEnum.class, "WidgetAttrEnum", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(widgetAttrEnumTypeEClass, WidgetAttrEnumType.class, "WidgetAttrEnumType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(widgetAttrEnumTypeSelectEClass, WidgetAttrEnumTypeSelect.class, "WidgetAttrEnumTypeSelect", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(widgetAttrDateEClass, WidgetAttrDate.class, "WidgetAttrDate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(widgetAttrTextEClass, WidgetAttrText.class, "WidgetAttrText", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(widgetSizeEClass, WidgetSize.class, "WidgetSize", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetSize_Type(), ecorePackage.getEString(), "type", null, 0, 1, WidgetSize.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widgetDisplayResultEClass, WidgetDisplayResult.class, "WidgetDisplayResult", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWidgetDisplayResult_Display_result(), ecorePackage.getEString(), "display_result", null, 0, 1, WidgetDisplayResult.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dateEClass, com.softtek.rdl.DATE.class, "DATE", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDATE_Date(), ecorePackage.getEString(), "date", null, 0, 1, com.softtek.rdl.DATE.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDATE_Now(), ecorePackage.getEString(), "now", null, 0, 1, com.softtek.rdl.DATE.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(actionSearchEClass, ActionSearch.class, "ActionSearch", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(actionAddEClass, ActionAdd.class, "ActionAdd", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(actionEditEClass, ActionEdit.class, "ActionEdit", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(actionDeleteEClass, ActionDelete.class, "ActionDelete", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(actionEClass, Action.class, "Action", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAction_Value(), ecorePackage.getEString(), "value", null, 0, 1, Action.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(actionsEClass, Actions.class, "Actions", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getActions_Action(), this.getAction(), null, "action", null, 0, -1, Actions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dbMapEntityEClass, DBMapEntity.class, "DBMapEntity", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDBMapEntity_Table(), ecorePackage.getEString(), "table", null, 0, 1, DBMapEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDBMapEntity_Dbmap_attrs(), this.getDBMapAttr(), null, "dbmap_attrs", null, 0, -1, DBMapEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dbMapAttrEClass, DBMapAttr.class, "DBMapAttr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(dbMapAttrIdentityEClass, DBMapAttrIdentity.class, "DBMapAttrIdentity", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDBMapAttrIdentity_Identity(), ecorePackage.getEString(), "identity", null, 0, 1, DBMapAttrIdentity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dbMapAttrAutoIdEClass, DBMapAttrAutoId.class, "DBMapAttrAutoId", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDBMapAttrAutoId_Autoid(), ecorePackage.getEString(), "autoid", null, 0, 1, DBMapAttrAutoId.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dbMapFieldEClass, DBMapField.class, "DBMapField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDBMapField_Table(), ecorePackage.getEString(), "table", null, 0, 1, DBMapField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDBMapField_Pk(), ecorePackage.getEString(), "pk", null, 0, 1, DBMapField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dataDomainEClass, DataDomain.class, "DataDomain", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDataDomain_Domain(), ecorePackage.getEString(), "domain", null, 0, 1, DataDomain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(businessRuleEClass, BusinessRule.class, "BusinessRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBusinessRule_Code(), ecorePackage.getEString(), "code", null, 0, 1, BusinessRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBusinessRule_Description(), ecorePackage.getEString(), "description", null, 0, 1, BusinessRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //RdlPackageImpl
