/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl.impl;

import com.softtek.rdl.RdlPackage;
import com.softtek.rdl.WidgetAttrEnumType;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Widget Attr Enum Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WidgetAttrEnumTypeImpl extends WidgetAttrEnumImpl implements WidgetAttrEnumType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WidgetAttrEnumTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdlPackage.Literals.WIDGET_ATTR_ENUM_TYPE;
  }

} //WidgetAttrEnumTypeImpl
