/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl.impl;

import com.softtek.rdl.RdlPackage;
import com.softtek.rdl.WidgetSortBy;
import com.softtek.rdl.WidgetTypeSelect;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Widget Type Select</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.impl.WidgetTypeSelectImpl#getType <em>Type</em>}</li>
 *   <li>{@link com.softtek.rdl.impl.WidgetTypeSelectImpl#getSortby <em>Sortby</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WidgetTypeSelectImpl extends WidgetAttrEnumTypeSelectImpl implements WidgetTypeSelect
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getSortby() <em>Sortby</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSortby()
   * @generated
   * @ordered
   */
  protected WidgetSortBy sortby;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WidgetTypeSelectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdlPackage.Literals.WIDGET_TYPE_SELECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RdlPackage.WIDGET_TYPE_SELECT__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WidgetSortBy getSortby()
  {
    return sortby;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSortby(WidgetSortBy newSortby, NotificationChain msgs)
  {
    WidgetSortBy oldSortby = sortby;
    sortby = newSortby;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RdlPackage.WIDGET_TYPE_SELECT__SORTBY, oldSortby, newSortby);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSortby(WidgetSortBy newSortby)
  {
    if (newSortby != sortby)
    {
      NotificationChain msgs = null;
      if (sortby != null)
        msgs = ((InternalEObject)sortby).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RdlPackage.WIDGET_TYPE_SELECT__SORTBY, null, msgs);
      if (newSortby != null)
        msgs = ((InternalEObject)newSortby).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RdlPackage.WIDGET_TYPE_SELECT__SORTBY, null, msgs);
      msgs = basicSetSortby(newSortby, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RdlPackage.WIDGET_TYPE_SELECT__SORTBY, newSortby, newSortby));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RdlPackage.WIDGET_TYPE_SELECT__SORTBY:
        return basicSetSortby(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RdlPackage.WIDGET_TYPE_SELECT__TYPE:
        return getType();
      case RdlPackage.WIDGET_TYPE_SELECT__SORTBY:
        return getSortby();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RdlPackage.WIDGET_TYPE_SELECT__TYPE:
        setType((String)newValue);
        return;
      case RdlPackage.WIDGET_TYPE_SELECT__SORTBY:
        setSortby((WidgetSortBy)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RdlPackage.WIDGET_TYPE_SELECT__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case RdlPackage.WIDGET_TYPE_SELECT__SORTBY:
        setSortby((WidgetSortBy)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RdlPackage.WIDGET_TYPE_SELECT__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case RdlPackage.WIDGET_TYPE_SELECT__SORTBY:
        return sortby != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(')');
    return result.toString();
  }

} //WidgetTypeSelectImpl
