/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl.impl;

import com.softtek.rdl.RdlPackage;
import com.softtek.rdl.WidgetDisplayResult;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Widget Display Result</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.softtek.rdl.impl.WidgetDisplayResultImpl#getDisplay_result <em>Display result</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WidgetDisplayResultImpl extends WidgetAttrImpl implements WidgetDisplayResult
{
  /**
   * The default value of the '{@link #getDisplay_result() <em>Display result</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplay_result()
   * @generated
   * @ordered
   */
  protected static final String DISPLAY_RESULT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDisplay_result() <em>Display result</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplay_result()
   * @generated
   * @ordered
   */
  protected String display_result = DISPLAY_RESULT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WidgetDisplayResultImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdlPackage.Literals.WIDGET_DISPLAY_RESULT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDisplay_result()
  {
    return display_result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDisplay_result(String newDisplay_result)
  {
    String oldDisplay_result = display_result;
    display_result = newDisplay_result;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RdlPackage.WIDGET_DISPLAY_RESULT__DISPLAY_RESULT, oldDisplay_result, display_result));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RdlPackage.WIDGET_DISPLAY_RESULT__DISPLAY_RESULT:
        return getDisplay_result();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RdlPackage.WIDGET_DISPLAY_RESULT__DISPLAY_RESULT:
        setDisplay_result((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RdlPackage.WIDGET_DISPLAY_RESULT__DISPLAY_RESULT:
        setDisplay_result(DISPLAY_RESULT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RdlPackage.WIDGET_DISPLAY_RESULT__DISPLAY_RESULT:
        return DISPLAY_RESULT_EDEFAULT == null ? display_result != null : !DISPLAY_RESULT_EDEFAULT.equals(display_result);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (display_result: ");
    result.append(display_result);
    result.append(')');
    return result.toString();
  }

} //WidgetDisplayResultImpl
