/**
 * generated by Xtext 2.16.0
 */
package com.softtek.rdl.impl;

import com.softtek.rdl.RdlPackage;
import com.softtek.rdl.WidgetAttr;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Widget Attr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WidgetAttrImpl extends MinimalEObjectImpl.Container implements WidgetAttr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WidgetAttrImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RdlPackage.Literals.WIDGET_ATTR;
  }

} //WidgetAttrImpl
