/**
 * generated by Xtext 2.16.0
 */
package com.softtek;

import com.softtek.RdlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RdlStandaloneSetup extends RdlStandaloneSetupGenerated {
  public static void doSetup() {
    new RdlStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
