/**
 * generated by Xtext 2.16.0
 */
package com.softtek.ide;

import com.softtek.ide.AbstractRdlIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RdlIdeModule extends AbstractRdlIdeModule {
}
