/*
 * generated by Xtext 2.16.0
 */
package com.softtek.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.softtek.ide.contentassist.antlr.internal.InternalRdlParser;
import com.softtek.services.RdlGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class RdlParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(RdlGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, RdlGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAbstractElementAccess().getAlternatives(), "rule__AbstractElement__Alternatives");
			builder.put(grammarAccess.getEntityFieldAccess().getAlternatives(), "rule__EntityField__Alternatives");
			builder.put(grammarAccess.getEntityTextConstraintAccess().getAlternatives(), "rule__EntityTextConstraint__Alternatives");
			builder.put(grammarAccess.getEntityTextFieldAttrAccess().getAlternatives(), "rule__EntityTextFieldAttr__Alternatives");
			builder.put(grammarAccess.getEntityLongTextFieldAttrAccess().getAlternatives(), "rule__EntityLongTextFieldAttr__Alternatives");
			builder.put(grammarAccess.getEntityDateFieldAttrAccess().getAlternatives(), "rule__EntityDateFieldAttr__Alternatives");
			builder.put(grammarAccess.getCardinalityUpperBoundAccess().getAlternatives(), "rule__CardinalityUpperBound__Alternatives");
			builder.put(grammarAccess.getEntityReferenceFieldAttrAccess().getAlternatives(), "rule__EntityReferenceFieldAttr__Alternatives");
			builder.put(grammarAccess.getEnumEntityAccess().getAlternatives(), "rule__EnumEntity__Alternatives");
			builder.put(grammarAccess.getEntityAttrAccess().getAlternatives(), "rule__EntityAttr__Alternatives");
			builder.put(grammarAccess.getConstraintRequiredAccess().getValueAlternatives_2_0(), "rule__ConstraintRequired__ValueAlternatives_2_0");
			builder.put(grammarAccess.getConstraintUniqueAccess().getValueAlternatives_2_0(), "rule__ConstraintUnique__ValueAlternatives_2_0");
			builder.put(grammarAccess.getWidgetExposedFilterAccess().getExposed_filterAlternatives_2_0(), "rule__WidgetExposedFilter__Exposed_filterAlternatives_2_0");
			builder.put(grammarAccess.getWidgetTypeAccess().getTypeAlternatives_2_0(), "rule__WidgetType__TypeAlternatives_2_0");
			builder.put(grammarAccess.getWidgetAttrAccess().getAlternatives(), "rule__WidgetAttr__Alternatives");
			builder.put(grammarAccess.getWidgetAttrEnumAccess().getAlternatives(), "rule__WidgetAttrEnum__Alternatives");
			builder.put(grammarAccess.getWidgetAttrEnumTypeAccess().getAlternatives(), "rule__WidgetAttrEnumType__Alternatives");
			builder.put(grammarAccess.getWidgetAttrDateAccess().getAlternatives(), "rule__WidgetAttrDate__Alternatives");
			builder.put(grammarAccess.getWidgetAttrTextAccess().getAlternatives(), "rule__WidgetAttrText__Alternatives");
			builder.put(grammarAccess.getWidgetSizeTypeAccess().getAlternatives(), "rule__WidgetSizeType__Alternatives");
			builder.put(grammarAccess.getWidgetDisplayResultAccess().getDisplay_resultAlternatives_2_0(), "rule__WidgetDisplayResult__Display_resultAlternatives_2_0");
			builder.put(grammarAccess.getBOOLEANAccess().getAlternatives(), "rule__BOOLEAN__Alternatives");
			builder.put(grammarAccess.getDATEAccess().getAlternatives(), "rule__DATE__Alternatives");
			builder.put(grammarAccess.getMONTHAccess().getAlternatives(), "rule__MONTH__Alternatives");
			builder.put(grammarAccess.getActionSearchAccess().getValueAlternatives_2_0(), "rule__ActionSearch__ValueAlternatives_2_0");
			builder.put(grammarAccess.getActionAddAccess().getValueAlternatives_2_0(), "rule__ActionAdd__ValueAlternatives_2_0");
			builder.put(grammarAccess.getActionEditAccess().getValueAlternatives_2_0(), "rule__ActionEdit__ValueAlternatives_2_0");
			builder.put(grammarAccess.getActionDeleteAccess().getValueAlternatives_2_0(), "rule__ActionDelete__ValueAlternatives_2_0");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getDBMapEntityAccess().getAlternatives_5(), "rule__DBMapEntity__Alternatives_5");
			builder.put(grammarAccess.getDBMapAttrAccess().getAlternatives(), "rule__DBMapAttr__Alternatives");
			builder.put(grammarAccess.getDBMapAttrAutoIdAccess().getAutoidAlternatives_2_0(), "rule__DBMapAttrAutoId__AutoidAlternatives_2_0");
			builder.put(grammarAccess.getDBMapFieldAccess().getAlternatives_5(), "rule__DBMapField__Alternatives_5");
			builder.put(grammarAccess.getDBMapFieldAccess().getPkAlternatives_5_1_3_0(), "rule__DBMapField__PkAlternatives_5_1_3_0");
			builder.put(grammarAccess.getModuleAccess().getGroup(), "rule__Module__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
			builder.put(grammarAccess.getEnumAccess().getGroup(), "rule__Enum__Group__0");
			builder.put(grammarAccess.getEnumLiteralAccess().getGroup(), "rule__EnumLiteral__Group__0");
			builder.put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
			builder.put(grammarAccess.getMethodDeclarationAccess().getGroup(), "rule__MethodDeclaration__Group__0");
			builder.put(grammarAccess.getStatementReturnAccess().getGroup(), "rule__StatementReturn__Group__0");
			builder.put(grammarAccess.getEntityTextConstraintDefAccess().getGroup(), "rule__EntityTextConstraintDef__Group__0");
			builder.put(grammarAccess.getEntityTextConstraintDefAccess().getGroup_3(), "rule__EntityTextConstraintDef__Group_3__0");
			builder.put(grammarAccess.getEntityTextFieldAccess().getGroup(), "rule__EntityTextField__Group__0");
			builder.put(grammarAccess.getEntityTextFieldAccess().getGroup_4(), "rule__EntityTextField__Group_4__0");
			builder.put(grammarAccess.getEntityLongTextFieldAccess().getGroup(), "rule__EntityLongTextField__Group__0");
			builder.put(grammarAccess.getEntityLongTextFieldAccess().getGroup_4(), "rule__EntityLongTextField__Group_4__0");
			builder.put(grammarAccess.getEntityDateFieldAccess().getGroup(), "rule__EntityDateField__Group__0");
			builder.put(grammarAccess.getEntityDateFieldAccess().getGroup_4(), "rule__EntityDateField__Group_4__0");
			builder.put(grammarAccess.getEntityDateFieldAttrAccess().getGroup_0(), "rule__EntityDateFieldAttr__Group_0__0");
			builder.put(grammarAccess.getEntityReferenceFieldAccess().getGroup(), "rule__EntityReferenceField__Group__0");
			builder.put(grammarAccess.getEntityReferenceFieldAccess().getGroup_9(), "rule__EntityReferenceField__Group_9__0");
			builder.put(grammarAccess.getEntityReferenceFieldAccess().getGroup_10(), "rule__EntityReferenceField__Group_10__0");
			builder.put(grammarAccess.getEntityImageFieldAccess().getGroup(), "rule__EntityImageField__Group__0");
			builder.put(grammarAccess.getEntityImageFieldAccess().getGroup_4(), "rule__EntityImageField__Group_4__0");
			builder.put(grammarAccess.getEntityFileFieldAccess().getGroup(), "rule__EntityFileField__Group__0");
			builder.put(grammarAccess.getEntityFileFieldAccess().getGroup_4(), "rule__EntityFileField__Group_4__0");
			builder.put(grammarAccess.getEntityEmailFieldAccess().getGroup(), "rule__EntityEmailField__Group__0");
			builder.put(grammarAccess.getEntityEmailFieldAccess().getGroup_4(), "rule__EntityEmailField__Group_4__0");
			builder.put(grammarAccess.getEntityDecimalFieldAccess().getGroup(), "rule__EntityDecimalField__Group__0");
			builder.put(grammarAccess.getEntityDecimalFieldAccess().getGroup_4(), "rule__EntityDecimalField__Group_4__0");
			builder.put(grammarAccess.getEntityIntegerFieldAccess().getGroup(), "rule__EntityIntegerField__Group__0");
			builder.put(grammarAccess.getEntityIntegerFieldAccess().getGroup_4(), "rule__EntityIntegerField__Group_4__0");
			builder.put(grammarAccess.getEntityCurrencyFieldAccess().getGroup(), "rule__EntityCurrencyField__Group__0");
			builder.put(grammarAccess.getEntityCurrencyFieldAccess().getGroup_4(), "rule__EntityCurrencyField__Group_4__0");
			builder.put(grammarAccess.getConstraintRequiredAccess().getGroup(), "rule__ConstraintRequired__Group__0");
			builder.put(grammarAccess.getConstraintUniqueAccess().getGroup(), "rule__ConstraintUnique__Group__0");
			builder.put(grammarAccess.getConstraintMaxLengthAccess().getGroup(), "rule__ConstraintMaxLength__Group__0");
			builder.put(grammarAccess.getConstraintMinLengthAccess().getGroup(), "rule__ConstraintMinLength__Group__0");
			builder.put(grammarAccess.getGlossaryAccess().getGroup(), "rule__Glossary__Group__0");
			builder.put(grammarAccess.getGlossaryNameAccess().getGroup(), "rule__GlossaryName__Group__0");
			builder.put(grammarAccess.getGlossaryDescriptionAccess().getGroup(), "rule__GlossaryDescription__Group__0");
			builder.put(grammarAccess.getWidgetLabelAccess().getGroup(), "rule__WidgetLabel__Group__0");
			builder.put(grammarAccess.getWidgetHelpAccess().getGroup(), "rule__WidgetHelp__Group__0");
			builder.put(grammarAccess.getWidgetExposedFilterAccess().getGroup(), "rule__WidgetExposedFilter__Group__0");
			builder.put(grammarAccess.getWidgetTypeAccess().getGroup(), "rule__WidgetType__Group__0");
			builder.put(grammarAccess.getWidgetTypeSelectAccess().getGroup(), "rule__WidgetTypeSelect__Group__0");
			builder.put(grammarAccess.getWidgetSortByAccess().getGroup(), "rule__WidgetSortBy__Group__0");
			builder.put(grammarAccess.getWidgetStartYearAccess().getGroup(), "rule__WidgetStartYear__Group__0");
			builder.put(grammarAccess.getWidgetEndYearAccess().getGroup(), "rule__WidgetEndYear__Group__0");
			builder.put(grammarAccess.getWidgetAccess().getGroup(), "rule__Widget__Group__0");
			builder.put(grammarAccess.getWidgetAccess().getGroup_3(), "rule__Widget__Group_3__0");
			builder.put(grammarAccess.getWidgetEnumAccess().getGroup(), "rule__WidgetEnum__Group__0");
			builder.put(grammarAccess.getWidgetEnumAccess().getGroup_3(), "rule__WidgetEnum__Group_3__0");
			builder.put(grammarAccess.getWidgetDateAccess().getGroup(), "rule__WidgetDate__Group__0");
			builder.put(grammarAccess.getWidgetDateAccess().getGroup_3(), "rule__WidgetDate__Group_3__0");
			builder.put(grammarAccess.getWidgetTextAccess().getGroup(), "rule__WidgetText__Group__0");
			builder.put(grammarAccess.getWidgetTextAccess().getGroup_3(), "rule__WidgetText__Group_3__0");
			builder.put(grammarAccess.getWidgetAttrEnumTypeSelectAccess().getGroup(), "rule__WidgetAttrEnumTypeSelect__Group__0");
			builder.put(grammarAccess.getWidgetAttrEnumTypeSelectAccess().getGroup_1(), "rule__WidgetAttrEnumTypeSelect__Group_1__0");
			builder.put(grammarAccess.getWidgetSizeAccess().getGroup(), "rule__WidgetSize__Group__0");
			builder.put(grammarAccess.getWidgetDisplayResultAccess().getGroup(), "rule__WidgetDisplayResult__Group__0");
			builder.put(grammarAccess.getDATEAccess().getGroup_0(), "rule__DATE__Group_0__0");
			builder.put(grammarAccess.getActionSearchAccess().getGroup(), "rule__ActionSearch__Group__0");
			builder.put(grammarAccess.getActionAddAccess().getGroup(), "rule__ActionAdd__Group__0");
			builder.put(grammarAccess.getActionEditAccess().getGroup(), "rule__ActionEdit__Group__0");
			builder.put(grammarAccess.getActionDeleteAccess().getGroup(), "rule__ActionDelete__Group__0");
			builder.put(grammarAccess.getActionsAccess().getGroup(), "rule__Actions__Group__0");
			builder.put(grammarAccess.getActionsAccess().getGroup_3(), "rule__Actions__Group_3__0");
			builder.put(grammarAccess.getDBMapEntityAccess().getGroup(), "rule__DBMapEntity__Group__0");
			builder.put(grammarAccess.getDBMapEntityAccess().getGroup_5_1(), "rule__DBMapEntity__Group_5_1__0");
			builder.put(grammarAccess.getDBMapEntityAccess().getGroup_5_1_2(), "rule__DBMapEntity__Group_5_1_2__0");
			builder.put(grammarAccess.getDBMapAttrIdentityAccess().getGroup(), "rule__DBMapAttrIdentity__Group__0");
			builder.put(grammarAccess.getDBMapAttrAutoIdAccess().getGroup(), "rule__DBMapAttrAutoId__Group__0");
			builder.put(grammarAccess.getDBMapFieldAccess().getGroup(), "rule__DBMapField__Group__0");
			builder.put(grammarAccess.getDBMapFieldAccess().getGroup_5_1(), "rule__DBMapField__Group_5_1__0");
			builder.put(grammarAccess.getDataDomainAccess().getGroup(), "rule__DataDomain__Group__0");
			builder.put(grammarAccess.getBusinessRuleAccess().getGroup(), "rule__BusinessRule__Group__0");
			builder.put(grammarAccess.getModelAccess().getModuleAssignment(), "rule__Model__ModuleAssignment");
			builder.put(grammarAccess.getModuleAccess().getNameAssignment_1(), "rule__Module__NameAssignment_1");
			builder.put(grammarAccess.getModuleAccess().getElementsAssignment_3(), "rule__Module__ElementsAssignment_3");
			builder.put(grammarAccess.getEnumAccess().getNameAssignment_1(), "rule__Enum__NameAssignment_1");
			builder.put(grammarAccess.getEnumAccess().getEnum_literalsAssignment_3(), "rule__Enum__Enum_literalsAssignment_3");
			builder.put(grammarAccess.getEnumLiteralAccess().getKeyAssignment_0(), "rule__EnumLiteral__KeyAssignment_0");
			builder.put(grammarAccess.getEnumLiteralAccess().getValueAssignment_2(), "rule__EnumLiteral__ValueAssignment_2");
			builder.put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
			builder.put(grammarAccess.getEntityAccess().getActionsAssignment_3(), "rule__Entity__ActionsAssignment_3");
			builder.put(grammarAccess.getEntityAccess().getGlossaryAssignment_4(), "rule__Entity__GlossaryAssignment_4");
			builder.put(grammarAccess.getEntityAccess().getDb_mapAssignment_5(), "rule__Entity__Db_mapAssignment_5");
			builder.put(grammarAccess.getEntityAccess().getEntity_fieldsAssignment_6(), "rule__Entity__Entity_fieldsAssignment_6");
			builder.put(grammarAccess.getEntityAccess().getEntity_methodsAssignment_7(), "rule__Entity__Entity_methodsAssignment_7");
			builder.put(grammarAccess.getMethodDeclarationAccess().getNameAssignment_1(), "rule__MethodDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getMethodDeclarationAccess().getDef_statementsAssignment_3(), "rule__MethodDeclaration__Def_statementsAssignment_3");
			builder.put(grammarAccess.getStatementReturnAccess().getEntityfieldAssignment_1(), "rule__StatementReturn__EntityfieldAssignment_1");
			builder.put(grammarAccess.getEntityTextConstraintDefAccess().getConstraintsAssignment_2(), "rule__EntityTextConstraintDef__ConstraintsAssignment_2");
			builder.put(grammarAccess.getEntityTextConstraintDefAccess().getConstraintsAssignment_3_1(), "rule__EntityTextConstraintDef__ConstraintsAssignment_3_1");
			builder.put(grammarAccess.getEntityTextFieldAccess().getNameAssignment_1(), "rule__EntityTextField__NameAssignment_1");
			builder.put(grammarAccess.getEntityTextFieldAccess().getAttrsAssignment_4_1(), "rule__EntityTextField__AttrsAssignment_4_1");
			builder.put(grammarAccess.getEntityTextFieldAttrAccess().getGlossaryAssignment_0(), "rule__EntityTextFieldAttr__GlossaryAssignment_0");
			builder.put(grammarAccess.getEntityTextFieldAttrAccess().getWidgetAssignment_1(), "rule__EntityTextFieldAttr__WidgetAssignment_1");
			builder.put(grammarAccess.getEntityTextFieldAttrAccess().getConstraintAssignment_2(), "rule__EntityTextFieldAttr__ConstraintAssignment_2");
			builder.put(grammarAccess.getEntityTextFieldAttrAccess().getDb_mapAssignment_3(), "rule__EntityTextFieldAttr__Db_mapAssignment_3");
			builder.put(grammarAccess.getEntityTextFieldAttrAccess().getData_domainAssignment_4(), "rule__EntityTextFieldAttr__Data_domainAssignment_4");
			builder.put(grammarAccess.getEntityTextFieldAttrAccess().getBusiness_ruleAssignment_5(), "rule__EntityTextFieldAttr__Business_ruleAssignment_5");
			builder.put(grammarAccess.getEntityLongTextFieldAccess().getNameAssignment_1(), "rule__EntityLongTextField__NameAssignment_1");
			builder.put(grammarAccess.getEntityLongTextFieldAccess().getAttrsAssignment_4_1(), "rule__EntityLongTextField__AttrsAssignment_4_1");
			builder.put(grammarAccess.getEntityLongTextFieldAttrAccess().getGlossaryAssignment_0(), "rule__EntityLongTextFieldAttr__GlossaryAssignment_0");
			builder.put(grammarAccess.getEntityLongTextFieldAttrAccess().getWidgetAssignment_1(), "rule__EntityLongTextFieldAttr__WidgetAssignment_1");
			builder.put(grammarAccess.getEntityLongTextFieldAttrAccess().getConstraintAssignment_2(), "rule__EntityLongTextFieldAttr__ConstraintAssignment_2");
			builder.put(grammarAccess.getEntityLongTextFieldAttrAccess().getDb_mapAssignment_3(), "rule__EntityLongTextFieldAttr__Db_mapAssignment_3");
			builder.put(grammarAccess.getEntityLongTextFieldAttrAccess().getData_domainAssignment_4(), "rule__EntityLongTextFieldAttr__Data_domainAssignment_4");
			builder.put(grammarAccess.getEntityLongTextFieldAttrAccess().getBusiness_ruleAssignment_5(), "rule__EntityLongTextFieldAttr__Business_ruleAssignment_5");
			builder.put(grammarAccess.getEntityDateFieldAccess().getNameAssignment_1(), "rule__EntityDateField__NameAssignment_1");
			builder.put(grammarAccess.getEntityDateFieldAccess().getAttrsAssignment_4_1(), "rule__EntityDateField__AttrsAssignment_4_1");
			builder.put(grammarAccess.getEntityDateFieldAttrAccess().getDefaultAssignment_0_2(), "rule__EntityDateFieldAttr__DefaultAssignment_0_2");
			builder.put(grammarAccess.getEntityDateFieldAttrAccess().getGlossaryAssignment_1(), "rule__EntityDateFieldAttr__GlossaryAssignment_1");
			builder.put(grammarAccess.getEntityDateFieldAttrAccess().getWidgetAssignment_2(), "rule__EntityDateFieldAttr__WidgetAssignment_2");
			builder.put(grammarAccess.getEntityDateFieldAttrAccess().getConstraintAssignment_3(), "rule__EntityDateFieldAttr__ConstraintAssignment_3");
			builder.put(grammarAccess.getEntityDateFieldAttrAccess().getDb_mapAssignment_4(), "rule__EntityDateFieldAttr__Db_mapAssignment_4");
			builder.put(grammarAccess.getEntityDateFieldAttrAccess().getData_domainAssignment_5(), "rule__EntityDateFieldAttr__Data_domainAssignment_5");
			builder.put(grammarAccess.getEntityDateFieldAttrAccess().getBusiness_ruleAssignment_6(), "rule__EntityDateFieldAttr__Business_ruleAssignment_6");
			builder.put(grammarAccess.getEntityReferenceFieldAccess().getNameAssignment_1(), "rule__EntityReferenceField__NameAssignment_1");
			builder.put(grammarAccess.getEntityReferenceFieldAccess().getSuperTypeAssignment_3(), "rule__EntityReferenceField__SuperTypeAssignment_3");
			builder.put(grammarAccess.getEntityReferenceFieldAccess().getLowerBoundAssignment_5(), "rule__EntityReferenceField__LowerBoundAssignment_5");
			builder.put(grammarAccess.getEntityReferenceFieldAccess().getUpperBoundAssignment_7(), "rule__EntityReferenceField__UpperBoundAssignment_7");
			builder.put(grammarAccess.getEntityReferenceFieldAccess().getOppositeAssignment_9_1(), "rule__EntityReferenceField__OppositeAssignment_9_1");
			builder.put(grammarAccess.getEntityReferenceFieldAccess().getAttrsAssignment_10_1(), "rule__EntityReferenceField__AttrsAssignment_10_1");
			builder.put(grammarAccess.getEntityReferenceFieldAttrAccess().getGlossaryAssignment_0(), "rule__EntityReferenceFieldAttr__GlossaryAssignment_0");
			builder.put(grammarAccess.getEntityReferenceFieldAttrAccess().getWidgetAssignment_1(), "rule__EntityReferenceFieldAttr__WidgetAssignment_1");
			builder.put(grammarAccess.getEntityReferenceFieldAttrAccess().getConstraintAssignment_2(), "rule__EntityReferenceFieldAttr__ConstraintAssignment_2");
			builder.put(grammarAccess.getEntityReferenceFieldAttrAccess().getDb_mapAssignment_3(), "rule__EntityReferenceFieldAttr__Db_mapAssignment_3");
			builder.put(grammarAccess.getEntityReferenceFieldAttrAccess().getData_domainAssignment_4(), "rule__EntityReferenceFieldAttr__Data_domainAssignment_4");
			builder.put(grammarAccess.getEntityReferenceFieldAttrAccess().getBusiness_ruleAssignment_5(), "rule__EntityReferenceFieldAttr__Business_ruleAssignment_5");
			builder.put(grammarAccess.getEntityImageFieldAccess().getNameAssignment_1(), "rule__EntityImageField__NameAssignment_1");
			builder.put(grammarAccess.getEntityImageFieldAccess().getAttrsAssignment_4_1(), "rule__EntityImageField__AttrsAssignment_4_1");
			builder.put(grammarAccess.getEntityFileFieldAccess().getNameAssignment_1(), "rule__EntityFileField__NameAssignment_1");
			builder.put(grammarAccess.getEntityFileFieldAccess().getAttrsAssignment_4_1(), "rule__EntityFileField__AttrsAssignment_4_1");
			builder.put(grammarAccess.getEntityEmailFieldAccess().getNameAssignment_1(), "rule__EntityEmailField__NameAssignment_1");
			builder.put(grammarAccess.getEntityEmailFieldAccess().getAttrsAssignment_4_1(), "rule__EntityEmailField__AttrsAssignment_4_1");
			builder.put(grammarAccess.getEntityDecimalFieldAccess().getNameAssignment_1(), "rule__EntityDecimalField__NameAssignment_1");
			builder.put(grammarAccess.getEntityDecimalFieldAccess().getAttrsAssignment_4_1(), "rule__EntityDecimalField__AttrsAssignment_4_1");
			builder.put(grammarAccess.getEntityIntegerFieldAccess().getNameAssignment_1(), "rule__EntityIntegerField__NameAssignment_1");
			builder.put(grammarAccess.getEntityIntegerFieldAccess().getAttrsAssignment_4_1(), "rule__EntityIntegerField__AttrsAssignment_4_1");
			builder.put(grammarAccess.getEntityCurrencyFieldAccess().getNameAssignment_1(), "rule__EntityCurrencyField__NameAssignment_1");
			builder.put(grammarAccess.getEntityCurrencyFieldAccess().getAttrsAssignment_4_1(), "rule__EntityCurrencyField__AttrsAssignment_4_1");
			builder.put(grammarAccess.getEntityAttrAccess().getGlossaryAssignment_0(), "rule__EntityAttr__GlossaryAssignment_0");
			builder.put(grammarAccess.getEntityAttrAccess().getWidgetAssignment_1(), "rule__EntityAttr__WidgetAssignment_1");
			builder.put(grammarAccess.getEntityAttrAccess().getConstraintAssignment_2(), "rule__EntityAttr__ConstraintAssignment_2");
			builder.put(grammarAccess.getEntityAttrAccess().getDb_mapAssignment_3(), "rule__EntityAttr__Db_mapAssignment_3");
			builder.put(grammarAccess.getEntityAttrAccess().getData_domainAssignment_4(), "rule__EntityAttr__Data_domainAssignment_4");
			builder.put(grammarAccess.getEntityAttrAccess().getBusiness_ruleAssignment_5(), "rule__EntityAttr__Business_ruleAssignment_5");
			builder.put(grammarAccess.getConstraintRequiredAccess().getValueAssignment_2(), "rule__ConstraintRequired__ValueAssignment_2");
			builder.put(grammarAccess.getConstraintUniqueAccess().getValueAssignment_2(), "rule__ConstraintUnique__ValueAssignment_2");
			builder.put(grammarAccess.getConstraintMaxLengthAccess().getValueAssignment_2(), "rule__ConstraintMaxLength__ValueAssignment_2");
			builder.put(grammarAccess.getConstraintMinLengthAccess().getValueAssignment_2(), "rule__ConstraintMinLength__ValueAssignment_2");
			builder.put(grammarAccess.getGlossaryAccess().getGlossary_nameAssignment_2(), "rule__Glossary__Glossary_nameAssignment_2");
			builder.put(grammarAccess.getGlossaryAccess().getGlossary_descriptionAssignment_4(), "rule__Glossary__Glossary_descriptionAssignment_4");
			builder.put(grammarAccess.getGlossaryNameAccess().getLabelAssignment_2(), "rule__GlossaryName__LabelAssignment_2");
			builder.put(grammarAccess.getGlossaryDescriptionAccess().getLabelAssignment_2(), "rule__GlossaryDescription__LabelAssignment_2");
			builder.put(grammarAccess.getWidgetLabelAccess().getLabelAssignment_2(), "rule__WidgetLabel__LabelAssignment_2");
			builder.put(grammarAccess.getWidgetHelpAccess().getHelpAssignment_2(), "rule__WidgetHelp__HelpAssignment_2");
			builder.put(grammarAccess.getWidgetExposedFilterAccess().getExposed_filterAssignment_2(), "rule__WidgetExposedFilter__Exposed_filterAssignment_2");
			builder.put(grammarAccess.getWidgetTypeAccess().getTypeAssignment_2(), "rule__WidgetType__TypeAssignment_2");
			builder.put(grammarAccess.getWidgetTypeSelectAccess().getTypeAssignment_2(), "rule__WidgetTypeSelect__TypeAssignment_2");
			builder.put(grammarAccess.getWidgetSortByAccess().getSortbyAssignment_2(), "rule__WidgetSortBy__SortbyAssignment_2");
			builder.put(grammarAccess.getWidgetStartYearAccess().getStartAssignment_3(), "rule__WidgetStartYear__StartAssignment_3");
			builder.put(grammarAccess.getWidgetEndYearAccess().getEndAssignment_3(), "rule__WidgetEndYear__EndAssignment_3");
			builder.put(grammarAccess.getWidgetAccess().getWidgetAssignment_0(), "rule__Widget__WidgetAssignment_0");
			builder.put(grammarAccess.getWidgetAccess().getAttrsAssignment_2(), "rule__Widget__AttrsAssignment_2");
			builder.put(grammarAccess.getWidgetAccess().getAttrsAssignment_3_1(), "rule__Widget__AttrsAssignment_3_1");
			builder.put(grammarAccess.getWidgetEnumAccess().getWidgetAssignment_0(), "rule__WidgetEnum__WidgetAssignment_0");
			builder.put(grammarAccess.getWidgetEnumAccess().getAttrsAssignment_2(), "rule__WidgetEnum__AttrsAssignment_2");
			builder.put(grammarAccess.getWidgetEnumAccess().getAttrsAssignment_3_1(), "rule__WidgetEnum__AttrsAssignment_3_1");
			builder.put(grammarAccess.getWidgetDateAccess().getWidgetAssignment_0(), "rule__WidgetDate__WidgetAssignment_0");
			builder.put(grammarAccess.getWidgetDateAccess().getAttrsAssignment_2(), "rule__WidgetDate__AttrsAssignment_2");
			builder.put(grammarAccess.getWidgetDateAccess().getAttrsAssignment_3_1(), "rule__WidgetDate__AttrsAssignment_3_1");
			builder.put(grammarAccess.getWidgetTextAccess().getWidgetAssignment_0(), "rule__WidgetText__WidgetAssignment_0");
			builder.put(grammarAccess.getWidgetTextAccess().getAttrsAssignment_2(), "rule__WidgetText__AttrsAssignment_2");
			builder.put(grammarAccess.getWidgetTextAccess().getAttrsAssignment_3_1(), "rule__WidgetText__AttrsAssignment_3_1");
			builder.put(grammarAccess.getWidgetAttrEnumTypeSelectAccess().getSortbyAssignment_1_1(), "rule__WidgetAttrEnumTypeSelect__SortbyAssignment_1_1");
			builder.put(grammarAccess.getWidgetSizeAccess().getTypeAssignment_2(), "rule__WidgetSize__TypeAssignment_2");
			builder.put(grammarAccess.getWidgetDisplayResultAccess().getDisplay_resultAssignment_2(), "rule__WidgetDisplayResult__Display_resultAssignment_2");
			builder.put(grammarAccess.getDATEAccess().getDateAssignment_0_1(), "rule__DATE__DateAssignment_0_1");
			builder.put(grammarAccess.getDATEAccess().getNowAssignment_1(), "rule__DATE__NowAssignment_1");
			builder.put(grammarAccess.getActionSearchAccess().getValueAssignment_2(), "rule__ActionSearch__ValueAssignment_2");
			builder.put(grammarAccess.getActionAddAccess().getValueAssignment_2(), "rule__ActionAdd__ValueAssignment_2");
			builder.put(grammarAccess.getActionEditAccess().getValueAssignment_2(), "rule__ActionEdit__ValueAssignment_2");
			builder.put(grammarAccess.getActionDeleteAccess().getValueAssignment_2(), "rule__ActionDelete__ValueAssignment_2");
			builder.put(grammarAccess.getActionsAccess().getActionAssignment_2(), "rule__Actions__ActionAssignment_2");
			builder.put(grammarAccess.getActionsAccess().getActionAssignment_3_1(), "rule__Actions__ActionAssignment_3_1");
			builder.put(grammarAccess.getDBMapEntityAccess().getTableAssignment_4(), "rule__DBMapEntity__TableAssignment_4");
			builder.put(grammarAccess.getDBMapEntityAccess().getDbmap_attrsAssignment_5_1_1(), "rule__DBMapEntity__Dbmap_attrsAssignment_5_1_1");
			builder.put(grammarAccess.getDBMapEntityAccess().getDbmap_attrsAssignment_5_1_2_1(), "rule__DBMapEntity__Dbmap_attrsAssignment_5_1_2_1");
			builder.put(grammarAccess.getDBMapAttrIdentityAccess().getIdentityAssignment_2(), "rule__DBMapAttrIdentity__IdentityAssignment_2");
			builder.put(grammarAccess.getDBMapAttrAutoIdAccess().getAutoidAssignment_2(), "rule__DBMapAttrAutoId__AutoidAssignment_2");
			builder.put(grammarAccess.getDBMapFieldAccess().getTableAssignment_4(), "rule__DBMapField__TableAssignment_4");
			builder.put(grammarAccess.getDBMapFieldAccess().getPkAssignment_5_1_3(), "rule__DBMapField__PkAssignment_5_1_3");
			builder.put(grammarAccess.getDataDomainAccess().getDomainAssignment_4(), "rule__DataDomain__DomainAssignment_4");
			builder.put(grammarAccess.getBusinessRuleAccess().getCodeAssignment_4(), "rule__BusinessRule__CodeAssignment_4");
			builder.put(grammarAccess.getBusinessRuleAccess().getDescriptionAssignment_8(), "rule__BusinessRule__DescriptionAssignment_8");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private RdlGrammarAccess grammarAccess;

	@Override
	protected InternalRdlParser createParser() {
		InternalRdlParser result = new InternalRdlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
