/*
 * generated by Xtext 2.16.0
 */
package com.softtek.tests

import com.google.inject.Inject
import com.softtek.rdl.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.junit.Ignore

@ExtendWith(InjectionExtension)
@InjectWith(RdlInjectorProvider)
class RdlParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	@Ignore
	def void loadModel() {
		println("Test --> RdlParsingTest.loadModel()");
		/*
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		*/
	}
}
